- azure-pipelines.yml
- src/mem/alloc.h
- src/mem/pagemap.h
- src/mem/remoteallocator.h
- src/test/func/memory/memory.cc
This PR fixes multiple issues with making 32bit compilation work on Windows. 
It adds 32 bit Windows builds to the CI. 
It does not address 32bit for other platforms.
> Windows 32bit build

- src/ds/mpscq.h
- src/mem/alloc.h
Changed the queue, so the names are more "standard".
> Updated to match documentation.

- src/pal/pal_windows.h
Fix the build for systematic testing.  Two variable declarations were accidentally deleted in the refactor.
> Systematic

- src/ds/bits.h
- src/mem/alloc.h
- src/mem/threadalloc.h
* Modified TLS code to have the slow path in a separate function
* Switch some sanity checks to debug only
> Two minor performance improvements

- src/pal/pal_bsd_aligned.h
@krytarowski, can you test this one please?
> NetBSD support

- src/mem/alloc.h
- src/mem/allocstats.h
> Fix stats underflow

- src/mem/allocconfig.h
- src/mem/metaslab.h
- src/mem/pagemap.h
Some more changes extracted from my CHERI preparation tree.
> Further CHERI prep

- src/mem/largealloc.h
- src/pal/pal_open_enclave.h
- src/test/func/fixed_region/fixed_region.cc
- src/test/func/two_alloc_types/main.cc
> Fix recent OpenEnclave + snmalloc Release build

- src/ds/address.h
- src/ds/bits.h
- src/ds/dllist.h
- src/mem/alloc.h
- src/test/func/fixed_region/fixed_region.cc
Happened in #138, problematic for certain platforms.
I need to work out a good way to build a test for this.
> Assert not going through the PAL

- CMakeLists.txt
- azure-pipelines.yml
- ci/linux_armhf
Picked armhf, for no particular reason. Is that ok, or do we want both armel and armhf?
> CI for both arms

- src/mem/largealloc.h
- src/mem/sizeclass.h
- src/override/malloc.cc
- src/test/func/malloc/malloc.cc
- src/test/func/memory/memory.cc
- src/test/func/sizeclass/sizeclass.cc
* Fixes #175
* Expands testing of realloc 
* Fixes a second bug found by expanding the testing due to incorrectly rounding large sizes.
> Large alloc fix

- src/ds/aba.h
- src/ds/helpers.h
- src/ds/mpscq.h
- src/mem/alloc.h
- src/mem/pagemap.h
- src/mem/pooled.h
- src/mem/remoteallocator.h
- src/mem/slowalloc.h
- src/pal/pal_consts.h
These changes make the code compile in clang10 with -std14.
> Various minor changes to aid compiling with std14

- azure-pipelines.yml
As per discussion in https://github.com/microsoft/snmalloc/pull/193
> Azure CI: Format: don't specify diff revision

- README.md
- src/ds/defines.h
- src/mem/alloc.h
- src/pal/pal.h
- src/pal/pal_freebsd_kernel.h
- src/pal/pal_open_enclave.h
- src/pal/pal_posix.h
- src/pal/pal_windows.h
Minor changes to alter the code gen for the better.  Has a much cleaner jump structure in Clang now.
> Improve code quality for alloc_size

- src/pal/pal_windows.h
- src/test/func/malloc/malloc.cc
Reverts microsoft/snmalloc#215
> Revert "fix mingw"

- src/pal/pal_posix.h
- src/pal/pal_windows.h
The POSIX PAL and in some configurations the Windows PAL overallocate
address space. If address space has become exhausted then this can lead
to issues, where the PAL fails, even though there is enough aligned
address space to satisfy the underlying request.
This commit tries increasingly smaller overallocation sizes in an
attempt to succeed in more cases.
> Implement PAL backoff

- src/test/func/memory/memory.cc
> add limited test

- src/mem/external_alloc.h
Haiku has a malloc_usable_size api but via the posix layer.
> pass through Haiku build fix.

- CMakeLists.txt
malloc_usable_size or similar unsupported.
> Solaris based system build fix.

- src/mem/alloc.h
Confirm that the client has given dealloc() a start-of-object pointer before
that pointer propagates very far (esp., before it enters the remote queues).
As these tests are not free, structure the code so that future interfaces can
skip over them if there's reason to be sure we're at the start of an object.
(On CHERI, for example, one could imagine using sealed pointers.)
For architectures with SSM/MTE, immediately after this test we can update the
memory granule to guard against double-frees; leave TODOs in place.
> NFC: Front "deallocating start of an object" tests

- CMakeLists.txt
- src/aal/aal.h
- src/aal/aal_concept.h
- src/aal/aal_consts.h
- src/ds/address.h
- src/ds/cdllist.h
- src/ds/concept.h
- src/ds/dllist.h
- src/ds/helpers.h
- src/ds/invalidptr.h
- src/ds/mpscq.h
- src/ds/ptrwrap.h
- src/mem/address_space.h
- src/mem/alloc.h
- src/mem/chunkmap.h
- src/mem/largealloc.h
- src/mem/mediumslab.h
- src/mem/metaslab.h
- src/mem/pagemap.h
- src/mem/slab.h
- src/mem/superslab.h
- src/override/malloc.cc
- src/pal/pal_posix.h
- src/test/func/external_pagemap/external_pagemap.cc
- src/test/func/malloc/malloc.cc
- src/test/func/memory/memory.cc
- src/test/func/pagemap/pagemap.cc
- src/test/func/two_alloc_types/main.cc
- src/test/perf/external_pointer/externalpointer.cc
Carves off the first 15 commits of #295 for separate review as requested.
> 202103 Pre-CHERIfication refactoring

- src/ds/aba.h
- src/ds/address.h
- src/ds/cdllist.h
- src/ds/mpmcstack.h
- src/mem/alloc.h
- src/mem/globalalloc.h
- src/mem/largealloc.h
- src/mem/pooled.h
Sorry; these four should have been part of #296 but I neglected to include them.  Hopefully similarly without objection.
> More pre-CHERIfication refactoring

- src/mem/freelist.h
On CHERI, the compiler will always issue a warning for
`reinterpret_cast<T*>(vaddr_t)` and similar expressions, and of course, if the
compiler can see far enough into the types, the presence of `if constexpr` will
not save us.  Therefore, lift the conditional out to two definitions of
`FreeObject::encode` using `std::enable_if_t` to gate which is used.
While in the neighborhood, use `address_t` rather than `uintptr_t`; the former
is the latter on all non-CHERI platforms, but is `vaddr_t` rather than
`uintcap_t` on CHERI.
> FreeObject: hide harder from the compiler, tweak types

- src/mem/alloc.h
- src/mem/allocslab.h
- src/mem/largealloc.h
- src/mem/mediumslab.h
- src/mem/metaslab.h
- src/pal/pal.h
- src/test/func/sandbox/sandbox.cc
Once again, pulling things that aren't strictly StrictProvenance-related out of #295 for stand-alone review.  No functional changes intended with this batch.
> Some more exhaust from the CHERIfication process

- src/pal/pal_concept.h
The test for NoAllocation/AlignedAllocation/neither was broken and this was
undetected until the sandbox demo came into being with its NoAllocation PAL
instance.  (Sadly, this remained undetected for so long because we can't
routinely build with C++20 because std::atomic_t<>'s initialization rules
changed in ways that make us require oodles and oodles of RAM at compile time.
This patch has been validated with -j1 on a machine with lots of RAM.)
Separately, it's possible that we end up here without `using namespace std`,
which seems like overkill.  So just use `std::size_t` ourselves within the PAL
Concept definition.
> Correct PAL Concept

- src/pal/pal_linux.h
> Enable overcommit for heuristic on Linux

- .github/workflows/main.yml
- README.md
The status badge should report the most recent status for the master
branch, not the most recent actions run.
> Fix status badge.

- src/pal/pal_haiku.h
with the beta3 release, and realizing MADV_DONTNEED is a "no-op"
MADV_FREE however is the only making sure the page range is discarded.
> PAL Haiku update.

- src/mem/corealloc.h
- src/mem/metaslab.h
- src/test/func/memory/memory.cc
- src/test/func/pagemap/pagemap.cc
None of these are expected to have functional implications.
> Miscellaneous accumulated trivia, 202108 edition

- src/mem/corealloc.h
- src/mem/metaslab.h
Introduce Metaslab::from_link(SlabLink*) to encapsulate the "container of"
dance.  Note that Metaslab was not a standard layout type prior to this change
(since both SlabLink and Metaslab defined non-static data members), and so the
reinterpret_cast<>s replaced here with ::from_link() were UB, but everyone lays
out classes as one expects so it was fine in practice.
Despite that Metaslab is now standard layout, we still don't fall back to the
inter-convertibility of a standard layout class and its first[*] data member
since we're going to want to put a common initial sequence across Metaslab and
ChunkRecord and the SlabLink isn't likely to be in it.
ETA: Yes, this is another case of the same thing as #270.
> Metaslab: SlabLink field rather than parent class

- CMakeLists.txt
> Install test headers.

- src/ds/mpmcstack.h
- src/ds/spmcstack.h
- src/mem/allocconfig.h
- src/mem/chunkallocator.h
- src/mem/corealloc.h
- src/mem/pool.h
- src/mem/remoteallocator.h
- src/test/func/domestication/domestication.cc
Provides a few minor changes that lead to improved performance of snmalloc2 branch.
> Optimisations

- .github/workflows/main.yml
- src/mem/corealloc.h
- src/test/func/release-rounding/rounding.cc
A few bits I found well experimenting with other stuff.
> Minor changes

- .gitignore
- src/override/rust.cc
Some features and clean ups for rust part
> Nits for rust release

- src/ds/defines.h
- src/mem/corealloc.h
- src/mem/freelist.h
- src/mem/localalloc.h
- src/mem/sizeclasstable.h
> Minor bits

- src/backend/address_space.h
- src/backend/globalconfig.h
- src/ds/flaglock.h
- src/ds/helpers.h
- src/mem/pool.h
> Add ownership checkings for FlagLock under debug

- src/test/func/thread_alloc_external/thread_alloc_external.cc
On Open Enclave having the `local_alloc` directly in thread-local
storage was causing a crash.  This changes the `local_alloc` to be
indirected, and thus puts less pressure on the thread-local storage.
The test also has deals with how to allocate before a thread-local
storage has been established.
> Change external thread_alloc example.

- src/pal/pal_posix.h
> use ::write and ::fsync in error path

- .github/workflows/main.yml
- CMakeLists.txt
- src/mem/external_alloc.h
- src/mem/remoteallocator.h
- src/pal/pal_ds.h
These are three issues highlighted by TSan.  This PR also enables TSan and UBSan in CI.
> Three fixes found by running TSan.

- .github/workflows/main.yml
- src/ds/aba.h
- src/ds/flaglock.h
- src/ds/mpmcstack.h
- src/mem/remoteallocator.h
This improves the CI for TSAN and fixes additional issues that it has discovered.
> More TSAN fixes

- .github/workflows/main.yml
> try enabling windows-2022

- src/backend/address_space.h
- src/backend/address_space_core.h
- src/backend/backend.h
- src/backend/backend_concept.h
- src/backend/fixedglobalconfig.h
- src/backend/pagemap.h
- src/ds/redblacktree.h
- src/mem/chunkallocator.h
- src/mem/corealloc.h
- src/mem/localalloc.h
- src/mem/remotecache.h
- src/test/func/pagemap/pagemap.cc
- src/test/func/redblack/redblack.cc
A series of refactorings to make it easier to replace the current naïve backend allorator with a slightly less naïve buddy allocator.
> Series of refactoring for introducing new backend allocator

- src/mem/corealloc.h
- src/mem/freelist.h
- src/test/func/malloc/malloc.cc
This is especially important on CHERI to avoid leaking capabilities to
the freelist. Also add a check in the malloc functional test that
there are no valid capabilities in the return allocation.
There is scope in future to add a dimension to `CapPtr` to track zeroing of allocations but this fixes the obvious big leak for now.
> Clear freelist pointers on allocation for CHERI or CHECK_CLIENT builds.

- src/mem/memcpy.h
It turns out it's useful to be able to vary the behaviour of small copies as a function of architecture as well, so refactor to pull that check into the arch hook.
Here's perf-memcpy-fast modified to run with this in place (unchecked and checked), the two implementations from FreeBSD (ppc-asm and ppc-vsx), and glibc (Debian package 2.33-7, platform).  This is a `--full_test` to get some idea of the spread.
Hiding the FreeBSD implementations and zooming in on the interesting region a bit...
> PowerPC64 memcpy arch tuning, take 2

- src/backend/commitrange.h
- src/backend/empty_range.h
- src/snmalloc_core.h
Also add a missing #pragma once that cause multiple includes to error.
> Expose ranges in snmalloc_core.

- src/snmalloc/backend/backend.h
- src/snmalloc/backend_helpers/pagemap.h
Hopefully this is roughly what you had in mind, David. Note that I had to make `PageMap::set_metaentry` public as well as the `concretePageMap` field so still things to do.
> Pagemap move

- src/snmalloc/backend/backend.h
- src/snmalloc/backend_helpers/largebuddyrange.h
- src/snmalloc/backend_helpers/pagemapregisterrange.h
- src/snmalloc/mem/metadata.h
- src/test/func/memory/memory.cc
> Fix for #506

- src/snmalloc/backend/backend.h
- src/snmalloc/backend_helpers/backend_helpers.h
- src/snmalloc/backend_helpers/logrange.h
- src/snmalloc/pal/pal_posix.h
- src/test/perf/contention/contention.cc
There is an infrequent crash on Win32.  This is some logging I was using to investigate it.  It also modifies the failing test to check for allocation failure.
> Debug win32

- src/snmalloc/aal/address.h
- src/snmalloc/backend_helpers/range_helpers.h
- src/snmalloc/mem/freelist.h
A few minor changes extracted from #570.
> Minor perf

- docs/PORTING.md
Just to fix a broken link in docs/PORTING.md
> Fix broken link in PORTING.md

- .github/workflows/main.yml
Fixes the FreeBSD side of #646
> FreeBSD CI.

- .github/workflows/main.yml
> Update NetBSD runner

- CMakeLists.txt
e.g. it's not available on MinGW's GCC
> cmake: look for rdynamic instead of hardcoding it

- src/snmalloc/pal/pal_windows.h
> [proxy](3/n) remove chrono dependency for windows

- .github/workflows/main.yml
Remove 20.04 from CI as it is no longer available.
> Remove 20.04 from CI
