src/mem/alloc.h, src/mem/globalalloc.h, src/mem/pool.h, src/mem/pooled.h
Minor refactor to clarify purpose of the pool.
=> Rename TypeAlloc to Pool

src/mem/slowalloc.h, src/override/malloc.cc, src/pal/pal_freebsd.h
With these changes, 32- and 64-bit userland builds, static and dynamically linked 64-bit versions are tested (32-bit ones are not, but hopefully work!).
=> Merge changes required for using snmalloc in FreeBSD libc

CMakeLists.txt, src/mem/largealloc.h, src/mem/pagemap.h, src/mem/remoteallocator.h
This PR makes the pagemap have OS_PAGE_SIZE alignment, and fixes the surrounding API.
Additionally, it fixes the encoding of sizeclasses into the top bits of remote allocation, to use the bottom bits, and shift the pointers up.  This allows a right signed shift to preserve the sign extended address space.
=> Fixes remote and pagemap

src/ds/helpers.h, src/mem/alloc.h, src/mem/metaslab.h, src/mem/slab.h, src/mem/superslab.h
General hardening of parts of the allocator:
* Prevent memory corruption in various places becoming a further gadget.
* Ensure we only access a valid meta slab index
* Remove some use of raw pointers to metaslabs.
=> Hardening allocator

src/override/malloc.cc
Fix a bug in memalign introduced in [8d07448](https://github.com/Microsoft/snmalloc/commit/8d074468ae6040a4f01d98b91276357a80d072ab).
=> Fix assertion failure in memalign

src/mem/alloc.h, src/mem/pool.h, src/mem/remoteallocator.h
This removes storing the sizeclass in the remote allocation.  On the most common paths, we touch the cache lines that contain the size class, so there is no noticeable perf improve from storing this in the block.
=> Simplification around remote allocation

CMakeLists.txt
RTTI makes the binaries bigger, exceptions make life harder for
optimisers.  Neither are actually used.
This doesn't preclude anything #including snmalloc.h with RTTI enabled,
it just disables it in the shim libraries and tests.
The FreeBSD libc builds were already doing this with no ill effect.
=> Disable rtti / exceptions on the non-Windows builds.

src/mem/largealloc.h, src/test/func/memory/memory.cc
This fixes a bug found by PR #20.
The PAL requires the values to be page aligned, but in a large alloc case they weren't.
=> Pal zero bug alignment

src/mem/alloc.h, src/override/malloc.cc
Introduce a `OnePastEnd` option for the pointer immediately after the
end of the allocation.  This simplifies some of the logic in callers,
where they wants to say 'is base + length safe to use?'.
Also restructure some of the other logic somewhat.
=> Tweaks to end bounds checking.

src/mem/alloc.h, src/mem/allocconfig.h, src/mem/baseslab.h, src/mem/largealloc.h, src/pal/pal.h, src/pal/pal_free_bsd_kernel.h, src/pal/pal_freebsd.h, src/pal/pal_linux.h, src/pal/pal_open_enclave.h, src/pal/pal_windows.h
This does not deallocate memory until the OS tells us that we are short
on memory, then tries to decommit all of the cached chunks (except for
the first page, used for the linked lists).
Nowhere near enough testing to commit to master yet!
PR submitted to push it through CI and see what I broke.
=> Initial cut at a lazy decommit strategy.

azure-pipelines.yml, src/mem/largealloc.h, src/pal/pal.h, src/pal/pal_apple.h, src/pal/pal_free_bsd_kernel.h, src/pal/pal_freebsd.h, src/pal/pal_linux.h, src/pal/pal_open_enclave.h, src/pal/pal_windows.h, src/test/func/fixed_region/fixed_region.cc, src/test/func/two_alloc_types/main.cc
This PR (which depends on #29) factors out the code for dealing with a PAL that doesn't know how to give you strongly aligned memory.  That then makes the Apple PAL simpler to write, so the next commit adds one and integrates it with the CI:
https://dev.azure.com/snmalloc/snmalloc/_build/results?buildId=190
=> Combination of the refactor align and add Apple changes

azure-pipelines.yml, src/mem/alloc.h, src/mem/allocconfig.h, src/mem/pagemap.h, src/override/malloc.cc, src/pal/pal_consts.h, src/test/func/two_alloc_types/alloc1.cc, src/test/func/two_alloc_types/alloc2.cc, src/test/func/two_alloc_types/main.cc
Now that we have a function for finding the pagemap that we can use across shared libraries, modify it to do some type checking and make some of the other code more resilient to importing a pagemap from a library without pulling in the symbol.
=> Pagemap access refactor

src/ds/bits.h, src/ds/dllist.h, src/ds/mpmcstack.h, src/ds/mpscq.h, src/mem/alloc.h, src/mem/allocconfig.h, src/mem/globalalloc.h, src/mem/largealloc.h, src/mem/metaslab.h, src/mem/pagemap.h, src/mem/pool.h, src/mem/sizeclasstable.h, src/mem/superslab.h, src/mem/threadalloc.h, src/override/malloc.cc, src/pal/pal_apple.h, src/pal/pal_freebsd.h, src/pal/pal_linux.h, src/test/func/malloc/malloc.cc
General code tidying to make auditing easier, mostly 
* Reducing uses of casts.
* Reducing standard library includes.
=> General code cleaning

src/ds/dllist.h, src/mem/metaslab.h
This is a generalisation of `std::nullptr_t` that allows non-0 values of
pointer-sized-but-not-a-pointer thing.  `DLList` now takes an
`InvalidPointer`, `nullptr_t`, or some other compatible class as a
sentinel value instead of a `uintptr_t`.
=> Add an explicit invalid pointer type.

src/pal/pal_windows.h
@nwf branch is failing for 32bit.  I suspect it is failing to allocate memory.  After adding the error message, the previous assert failure went away, but now we get no information.  Adding a fflush to see if we can actually see the OOM error.
=> Added a fflush to the error message.

src/ds/helpers.h, src/mem/allocstats.h, src/mem/largealloc.h, src/mem/threadalloc.h
Fixed some statistics and made them automatically print atexit.
=> Made the statistics print atexit

CMakeLists.txt, src/mem/alloc.h, src/mem/allocconfig.h, src/mem/metaslab.h, src/mem/slab.h
Will detect corruption caused by either
* Use-after-free
* Double-free
Neither is comprehensive.  Full temporal safety is not possible.
This just aids with debugging.
=> A few checks for easy corruptions

src/ds/dllist.h, src/mem/alloc.h, src/mem/slab.h
This commit changes the strategy for finding a free list from
a stack to a queue.  This tends to avoid the slow path considerably more.
It has some memory overheads.
TOOD:  We should move the bump allocation data out of the metaslab and
into the allocator.  At the moment, the slab contains the bump allocation
data, we should move this into the allocator, as it only ever has one slab
it is bump allocating from per sizeclass.
=> Use a queue of slabs for free lists

src/mem/alloc.h, src/mem/largealloc.h, src/mem/threadalloc.h, src/pal/pal.h, src/pal/pal_apple.h, src/pal/pal_consts.h, src/pal/pal_freebsd.h, src/pal/pal_linux.h, src/test/perf/external_pointer/externalpointer.cc
* Move to using FlatPageMap by default on platforms, which lazily commit memory.
* Minor changes to inlining behaviour for better codegen.
=> Minor opts

src/ds/helpers.h, src/mem/alloc.h, src/mem/threadalloc.h, src/test/func/fixed_region/fixed_region.cc, src/test/func/memory/memory.cc, src/test/perf/contention/contention.cc, src/test/perf/external_pointer/externalpointer.cc, src/test/perf/singlethread/singlethread.cc
Made the API so that get always returns an initialised Alloc*.  Added
new fast path that doesn't perform checking, but can lead to very slow
behaviour if called and reused.
=> Improved ThreadAlloc::get API

src/override/malloc.cc, src/override/new.cc
This may return the GlobalPlaceholder, in which case the slow path will
be used, initializing the real thread local allocator.
=> Use get_noncachable in malloc/new overrides.

src/override/malloc.cc, src/pal/pal.h, src/pal/pal_bsd.h, src/pal/pal_freebsd.h, src/pal/pal_openbsd.h
Cannot enforce alignment so we just check its correctness.
=> Basic OpenBSD backend support.

src/mem/alloc.h, src/override/malloc.cc
The pagemap global is now an inline static of a template class, so that
we will see different symbols for the different types.
Issue #84 showed that it's possible to compile two compilation units
with different pagemaps, link them together, and have them attempt to
interpret the global pagemap as two different types.  This change should
make that impossible.
Also make the `pagemap()` function static so that it can be used from
static functions, avoiding other things that directly reference the
global pagemap.
=> Make the pagemap global typed.

src/mem/alloc.h
=> Typo in assertion.

src/mem/alloc.h, src/mem/globalalloc.h
This PR does
* Fix a memory leak during allocator creation, if the first allocation is the same size as the message queue stub;
* Provides a more resilient debug_check_empty, that does not depend on statistics being enabled.
=> Memory leak

src/mem/threadalloc.h
If we are using USE_MALLOC pass through, then ThreadAlloc::get() can
cause an allocation inside snmalloc still, as it builds the thread
local allocator, which allocs a single stub allocation, using
the underlying allocator. This means that ASAN would detect a
leak in a client, even though the client program has none.
This change stops us ever allocating allocators, if we are passing
through calls to an underlying allocator.
=> Modified pass through

src/mem/threadalloc.h
This is required so that we can replace the thread allocator during
setup for the library compartmentalisation case.
=> Make the get_reference() method on ThreadAlloc public.

azure-pipelines.yml, src/mem/alloc.h, src/mem/metaslab.h, src/mem/sizeclass.h, src/mem/slab.h, src/mem/superslab.h
These two changes reduce the fast path for deallocation from 34 instructions on Linux with Clang to 25 instructions.  There are two key changes
* When a slab is full, set its 'used' count to 1.  This allows the detecting leaving full, and entering empty to be the same check.
* Expand the meta-data to contain a full pointer to the free list, not a relative 16 bit pointer.  This reduces the arithmetic required on the fast path.
=> Code quality for `free`

src/mem/alloc.h, src/mem/chunkmap.h, src/mem/globalalloc.h, src/mem/pagemap.h, src/mem/threadalloc.h, src/override/malloc.cc
I'm certain there's something wrong with this PR, but I am not certain what, exactly.
I found it confusing that there were two things that called themselves PageMap and kept tripping over the difference when working on #41.  So, in order to reduce my tripping rate and in hopes that I might help others do the same, I propose that we rename the `alloc.h` Pagemap thing a Slabmap.  Not great, but at least different.
Having done that, it seemed to make sense to ensure that all accesses from the Allocator to the Pagemap were via the Slabmap.  And then it became apparent that everything was static, in fact, and so some additional cleanups were possible.
I suspect there is something I'm not getting; perhaps a different, out-of-tree setting for `SNMALLOC_DEFAULT_PAGEMAP` breaks this?  In any case, …
=> Deconflate "pagemap" 

CMakeLists.txt
In some platforms, it is rather amd64 than the more common x86_64,
thus missing to rightfully set this flag.
=> atomic swap 16 flag missing fix.

src/aal/aal.h, src/aal/aal_x86.h, src/ds/flaglock.h, src/ds/mpscq.h, src/mem/alloc.h, src/mem/allocstats.h, src/mem/chunkmap.h, src/mem/largealloc.h, src/mem/metaslab.h, src/mem/pagemap.h, src/pal/pal.h, src/test/perf/contention/contention.cc
And use them to gate `POISON`-ing pointers when `CHECK_CLIENT` is defined.  The bulk of the change is just stylistic to normalize case and the use of templated vardecls.
This extracts some small part of conversations had in #105 for incremental review.
=> Introduce AAL feature flags

src/mem/alloc.h
GCC has some aggressive warnings that can be imprecise for checking array bounds access.  This commit converts an assert to an assume to remove the warning.
I do not have GCC 9 to test this, but it follows a similar pattern to we have seen with other versions of GCC.  Should address #108.
=> Fix GCC 9 error.

src/override/malloc.cc
snmalloc has natural alignment for each sizeclass, this means that we can search for a sizeclass larger then the requested sizeclass whose natural alignment meets that specified by the call.
This is currently used in a single place, so was directly written into `memalign`. With #109 there is a wish to make a larger API surface that supports alignment.  This PR is intended to make that easier.
=> Small refactoring of code for finding a sizeclass for an alignment

src/mem/alloc.h
For languages like Verona or Rust, the deallocation calls know the
size of the object originally requested.  This change optimises that
code path to create a much better fast path.
=> Improve codegen for sized free.

CMakeLists.txt, azure-pipelines.yml, src/ds/aba.h, src/ds/bits.h, src/ds/defines.h, src/mem/remoteallocator.h, src/pal/pal_windows.h, src/test/setup.h
Fixes a few places where Clang complains about Windows specific code,
and also uses macros supported by Clang on Windows.  A few places
separating platform and compiler specific code, as MSVC and WIN32 were
used interchangably previously.
=> Make snmalloc build on Windows with Clang

CMakeLists.txt
find_program can do that for us. Additionally that loop was resetting the CLANG_FORMAT every time ninja was run, making it impossible to pass a specific -DCLANG_FORMAT=... to cmake.
I've tried version 6 to 8 and formatting remains stable. clang 9 is when it breaks down because of AfterCaseLabel.
=> Don't use our own loop to find clang-format

src/ds/helpers.h, src/mem/alloc.h, src/mem/allocconfig.h, src/mem/largealloc.h, src/mem/mediumslab.h, src/mem/metaslab.h, src/mem/slab.h, src/mem/superslab.h
This PR primarily fixes a performance issue on Windows where Commit (NotifyUsing) was called too often. 
The other commits tidy the decommit code to remove an unused poorly performing strategy, and refactor the code.
=> Improvements to Decommit Strategies

src/mem/alloc.h, src/mem/largealloc.h, src/mem/slab.h, src/mem/superslab.h, src/test/perf/low_memory/low-memory.cc
The low-memory notification was getting into an infinite loop.  This
fixes the loop termination, and provides a test for platforms which
support low-memory notification.
=> Issue with low-memory notification

CMakeLists.txt, README.md, src/mem/alloc.h, src/mem/largealloc.h, src/mem/sizeclass.h, src/mem/slab.h, src/mem/superslab.h, src/override/malloc.cc, src/pal/pal_apple.h, src/pal/pal_bsd_aligned.h, src/pal/pal_freebsd_kernel.h, src/pal/pal_open_enclave.h, src/pal/pal_posix.h, src/pal/pal_windows.h, src/test/func/fixed_region/fixed_region.cc, src/test/func/malloc/malloc.cc, src/test/func/two_alloc_types/main.cc
This makes all large allocations aligned to their size next power of two size.
This introduces a new strategy for aligning blocks on platforms without a way to fetched aligned virtual memory (e.g. VirtualAlloc2, or mmap with MAP_ALIGNED).
To aid in debugging also uses mprotect to switch off unused pages in debug on posix platforms. This enables better testing of the Commit/Decommit code from Posix platforms.
=> Make Large allocations naturally aligned

.clang-format, CMakeLists.txt, azure-pipelines.yml, src/ds/address.h, src/ds/bits.h, src/mem/slab.h
With clangformat9 the AfterCaseLabel is introduced.
And this defaults to false, but our code is formatted
implicitly with this set to true.
PRs to Verona and Snmalloc are being formatted with clangformat9,
and this is causing complexity. Let's move forward to clangformat9
in CI.
=> Update to use clangformat9

src/mem/globalalloc.h, src/mem/largealloc.h, src/mem/pagemap.h, src/mem/pool.h, src/mem/threadalloc.h, src/override/malloc.cc, src/pal/pal_open_enclave.h, src/test/func/fixed_region/fixed_region.cc, src/test/func/thread_alloc_external/thread_alloc_external.cc, src/test/perf/low_memory/low-memory.cc
These changes are to reduce the C++ runtime calls when the TLS state is managed externally.
This enables the code to be included in really restricted build environments such as Open Enclave where the allocator is needed before any of the C++ library is available.
The primary changes are to remove
```
GlobalPlaceHolder
```
as a global if not needed, and to convert 
```
default_memory_provider
```
from a C++ global with initialisation, into a pointer with our custom `Singleton` constructor.  This removes calls to 
```
__cxa_guard_acquire
```
and 
```
__cxa_guard_release
```
=> Removing some calls into the C++ runtime

src/mem/largealloc.h, src/pal/pal_consts.h, src/pal/pal_windows.h, src/test/perf/low_memory/low-memory.cc
On platforms that support low-memory notifications register callbacks
that perform lazy decommit. This allows idle processes to return memory
to the OS. Without incurring the cost of constantly committing and
decommitting memory.
=> Make Lazy Decomit asynchronous

azure-pipelines.yml, src/ds/defines.h, src/mem/largealloc.h
The bootstrapping allocator needs to perform a memcpy to bypass the
removed move constructors on std::atomic.  This is safe as there is no
concurrency at this point, but GCC is unhappy with this.
This commit moves CI to GCC8 and disables this warning for that line.
=> Address GCC8 warning

src/mem/alloc.h, src/mem/allocconfig.h, src/mem/globalalloc.h
This performs a small refactor on the remote dealloc path to split the common case out.
=> Remote dealloc refactor.

azure-pipelines.yml
I picked 10.15, since that's the newest, I don't know if 10.14 should also be covered.
=> Update the macOS image, since 10.13 is going out of support

azure-pipelines.yml, ci/linux_x64
Linux CI in docker, groundwork to add QEmu/ARM build, and clang upgrade along the way.
Somewhat slower than before because Pipelines still does not have an image cache, but builds are substantially more reproducible, which is sometimes nice.
=> Containerise Linux build

CMakeLists.txt, src/aal/aal_arm.h, src/pal/pal_linux.h
This is not hooked up to anything yet.  Once @achamayou has completed the containerised build #145, then we can add the AARCH64 QEMU build, and this will be used.
=> Workaround for QEMU behaviour.

src/ds/address.h, src/mem/allocconfig.h
The remote batch size has not changed since the fast path optimisations.
The optimisations mean we are checking the queue considerably less
often, so the batch should be larger.  This has a dramatic improvement
on performance on a few of the mimalloc microbenchmarks.
It is set to 4096 as this should cover the worse case scenario of only
remote deallocation at 16 bytes for the 2^16 slab size.
=> Increase Remote batch size

difference.md, src/ds/address.h, src/ds/bits.h, src/ds/cdllist.h, src/ds/dllist.h, src/ds/helpers.h, src/mem/alloc.h, src/mem/allocstats.h, src/mem/globalalloc.h, src/mem/largealloc.h, src/mem/metaslab.h, src/mem/pagemap.h, src/mem/pool.h, src/mem/slab.h, src/mem/superslab.h, src/mem/threadalloc.h, src/pal/pal_consts.h, src/pal/pal_windows.h, src/test/func/first_operation/first_operation.cc, src/test/perf/low_memory/low-memory.cc
* Make separate bump allocator ptr per thread and size class.
- Now a slab in the per-class list is guaranteed to have at least one free allocation, not including 
bump allocation.
- This enables more separation between how we are trying to find memory
* Refactor code to 
- Separate checks and slow paths to favour tail calls
- Generally make all slow paths tail calls to improve codegen
The general form of allocation is now
1. Local free list for this allocator
2. Grab next free list for this allocator
3. Bump allocate from local bump ptr
4. Grab new slab to bump allocate from
There are special cases interleaved into this
* Handle message queue
* If the thread local allocator needs initialising.
The first occurs between 1 and 2, and the second occurs between, 3 and 4.
=> Improve slow path performance for allocation

src/mem/largealloc.h, src/mem/slab.h, src/pal/pal_linux.h
* Use NoZero for fresh pages
* MADV_DONTNEED only use for greater than a whole slab
* Simplify free list threading code
=> Small changes

src/mem/alloc.h
Ensure that the size deallocated with is the correct size. If the size
supplied is wrong, then internal invariants can break.
=> Add checks for deallocation with size

CMakeLists.txt, azure-pipelines.yml, src/ds/aba.h, src/ds/defines.h, src/ds/mpmcstack.h, src/mem/alloc.h, src/mem/globalalloc.h, src/mem/pool.h, src/mem/pooled.h, src/mem/threadalloc.h, src/pal/pal.h, src/pal/pal_posix.h, src/test/func/first_operation/first_operation.cc
If an allocation or deallocation occurs during TLS teardown, then it is
possible for a new allocator to be created and then this is leaked. On
the mimalloc-bench mstressN benchmark this was observed leading to a
large memory leak.
This fix, detects if we are in the TLS teardown phase, and if so,
the calls to alloc or dealloc must return the allocator once they have
perform the specific operation.
[Add:] Also fixes unimplemented ABA primitive for ARM.  Currently uses locking.
[Add:] Some debug infrastructure to deal with Posix platforms.
=> Defensive code for alloc/dealloc during TLS teardown

src/ds/aba.h
These are used by the Verona runtime.
=> Add back the peek methods to ABA.

src/ds/aba.h, src/ds/defines.h, src/ds/helpers.h
This aims to address
https://github.com/openenclave/openenclave/issues/2802
@jhand2, @anakrish, @achamayou could someone try this branch to see if it fixes the issues?
=> Addressing OE linking issues when built with GCC

CMakeLists.txt, src/mem/alloc.h, src/mem/largealloc.h, src/test/func/first_operation/first_operation.cc, src/test/func/memory/memory.cc
The recent changes to the call-backs did not correctly pass the template parameters. This PR
* Adds a test to cover this case
* Passes the template parameters
* Call more specific entry points
* Re-enables GCC warning as we no longer trip up the spurious warning.
=> Callback fixes

azure-pipelines.yml, ci/linux_x86, src/ds/aba.h
We only need to CAS 2 pointers, which is always possible on x86.
This uses the `plietar/snmalloc-build_linux_x86:latest` docker image, obviously that should be changed to something under snmallocciteam.
=> Don't require 16-byte CAS on x86.

src/override/new.cc
The core snmalloc code assumes if you know the size, then it is not
nullptr. However, the C++ delete operator can be called with nullptr.
This change checks for that case.
=> Fix sized delete of nullptr

src/test/perf/contention/contention.cc
It is important, in test_tasks_f, that the store of the size to the
allocated block be made visible to other processors before the store of
the pointer itself.  Otherwise, other cores are justified in reading
junk.
This manifests on PowerPC as tripping the "Deallocating with incorrect
size supplied" assertion in alloc.h:/check_size because the value read
from the allocated block may not be a size but rather an internal queue
pointer, which is implausibly large, as sizes go.
=> test/contention: release size store first

CMakeLists.txt, src/pal/pal_posix.h
On FreeBSD, this notably requires the use of -lexecinfo, as backtrace()
is not available in -lc.  Rather than testing in C, test in cmake.
=> Use cmake to find backtrace()

src/ds/address.h, src/mem/alloc.h, src/mem/largealloc.h, src/mem/superslab.h
This should produce equivalent code everywhere and more obviously preserves provenance where desired.  Ultimately, eliminate `pointer_cast` entirely since it won't make sense to cast an address back to a pointer on CHERI platforms.
=> Use pointers, not addresses, in more places

src/aal/aal_x86_sgx.h
Fix the main remaining problem that prevents building oesnmalloc with -nostdinc. There's still a issue with the order in which headers are copied in the OE build but that's nothing to do with snmalloc.
Paging @anakrish because I can't work how to add him to Reviewers for some reason.
It is probably worth noting that this can be removed if/when 
a subset of https://github.com/openenclave/openenclave/issues/1766 is implemented in OE. That's been open for over a year though, so I would still like to have this change considered.
=> Make up for the lack of intrinsic headers in Open Enclave

azure-pipelines.yml, src/aal/aal.h, src/ds/cdllist.h
CHERI will assert StrictProvenance (probably via AAL Mixin) and we can gate on that everywhere we need.
One such example is the contents of the CDDList nodes, where on non-StrictProvenance architectures, a relative encoding of the next pointer allows for tolerance of zero-initialized (and not constructed) values.  For StrictProvenance, point explicitly at the next element but accept `nullptr` in lieu of `this` as the empty case.
With these (atop the other PRs I have open), we're back to being able to at least minimally run `snmalloc` on CHERI, but without capability bounds being enforced (that is, all pointers returned always authorize access to the entire underlying large allocation).  Still, it's nice to be doing this in a way of which upstream approves, this time. :)
=> Introduce AAL StrictProvenance flag, factor CDLList

CMakeLists.txt
Despite the comment, the cmakelist will in fact take "clang-format" and use it even if it's pre-9 and incompatible.
As a pre-9 user (a choice dictated by dependencies I have no control over), this is my preferred fix. I suppose adjusting the comment to match what the cmakelist does would also work.
=> Fix clang-format lookup to do what the comment says

src/aal/aal.h, src/ds/address.h, src/ds/dllist.h
On CHERI, we will want `address_t` to be `vaddr_t`, an integer type big enough to store an address but that cannot carry provenance (i.e., is too small to hold a capability).
=> Allow the AAL to define address_t

src/aal/aal.h, src/aal/aal_arm.h, src/aal/aal_powerpc.h, src/aal/aal_x86.h, src/aal/aal_x86_sgx.h, src/mem/alloc.h, src/mem/allocconfig.h, src/mem/mediumslab.h, src/mem/sizeclass.h, src/pal/pal.h, src/pal/pal_apple.h, src/pal/pal_bsd.h, src/pal/pal_freebsd_kernel.h, src/pal/pal_linux.h, src/pal/pal_open_enclave.h, src/pal/pal_plain.h, src/pal/pal_posix.h, src/pal/pal_windows.h
At least the latter half is necessary for Debian/PowerPC64 support.
The first commit here should have no functional changes and just lay the groundwork.  Admittedly, tho', it's selected out of a much larger mass of changes, so perhaps I've missed something.  Let's see what CI says.
Should we add a check to `pal_posix` at startup that `OS_PAGE_SIZE` is divisible by `sysconf(_SC_PAGESIZE)`?
=> Move OS_PAGE_SIZE to PAL, add Linux PowerPC w/ 64KiB pages

src/aal/aal_arm.h
The ARM AAL was including `<iostream>`, this is unnecessary, and only
`<cstddef>` should be required for `size_t`.
Fixes #199.
=> Remove iostream from ARM aal.

src/pal/pal.h, src/pal/pal_open_enclave.h
The Pal should include address.h, this was masked as other Pals included
it, but are only included for simulating OE scenarios, rather than
the actual build for OE.
=> Fix includes for the OE Pal.

CMakeLists.txt
Turn `-march=native` off by default. This makes binaries more portable,
but may harm performance. However, fast paths look unaltered
Fixes 204.
=> Make binaries more compatible by default

src/pal/pal_open_enclave.h, src/test/func/fixed_region/fixed_region.cc, src/test/func/two_alloc_types/alloc1.cc, src/test/func/two_alloc_types/main.cc
PALOpenEnclave object is lazily constructed. I couldn't
figure out a straight-forward way to pass the heap bounds to
the constructor of PALOpenEnclave object.
As an alternative, store the bounds in class-static members of a template
class.
- two_alloc_types/main.cc
OE use of snmalloc is renamed to snmalloc_enclave.
Declare oe_base and oe_end inline variables in snmalloc_enclave
namespace and initialize them.
- fixed_region/fixed_region.cc
Initialize oe_base and oe_end variables.
Cache the starting value of oe_base in orig_oe_base and
use that for asserting that the allocated memory lies
within the PAL heap. This is because, in pal_open_enclave.h,
reserve will change the value of oe_base.
CC: @achamayou 
Signed-off-by: Anand Krishnamoorthi <anakrish@microsoft.com>
=> OpenEnclave PAL: Store enclave heap base/end in inline variables.

README.md, src/mem/address_space.h, src/mem/largealloc.h, src/pal/pal_apple.h, src/pal/pal_bsd_aligned.h, src/pal/pal_freebsd_kernel.h, src/pal/pal_open_enclave.h, src/pal/pal_posix.h, src/pal/pal_windows.h
This change brings in a new approach to managing address space.
It wraps the Pal with a power of two reservation system, that
guarantees all returned blocks are naturally aligned to their size. It
either lets the Pal perform aligned requests, or over allocates and
splits into power of two blocks.
=> Add AddressSpaceManager

README.md, src/pal/pal_apple.h, src/pal/pal_haiku.h, src/pal/pal_posix.h
The Apple and Haiku PALs both had *almost* identical code to the POSIX
PAL, differing only in some small argument variables.  This is fragile
and easy to accidentally get out of sync.  For example, the changes to
`reserve_at_least` involved copying identical code into multiple PALs
and it's easy to accidentally miss one.
This change introduces two optional fields on POSIX-derived PALs:
- `default_mmap_flags` allows a PAL to provide additional `MAP_*`
flags to all `mmap` calls.
- `anonymous_memory_fd` allows the PAL to override the default file
descriptor used for memory mappings.
If a PAL does not provide these, default values are used.
=> Reduce code duplication.

src/pal/pal.h, src/pal/pal_posix.h, src/pal/pal_solaris.h
MAP_NORESERVE flag usage for memory over commit permitted only
in the mmap context.
=> Illumos systems/Solaris support.

src/mem/pagemap.h
FlatPagemap computes the size of its internal `top` array as if it needed an
entry per byte, rather than an entry per instance of its template type T.  In
practice. T has always been uint8_t so far, so this hasn't mattered, but when
we use a larger type, suddenly FlatPagemap balloons to much larger than needed.
=> FlatPagemap: Stop allocating way more space than needed

src/test/func/memory/memory.cc
Build complain about wrong header inclusion, sys/wait.h ough to be
instead.
=> Linux/musl test: build fix proposal.

CMakeLists.txt, README.md, src/ds/aba.h, src/ds/concept.h, src/mem/address_space.h, src/mem/alloc.h, src/mem/largealloc.h, src/mem/mediumslab.h, src/mem/pool.h, src/mem/slab.h, src/pal/pal.h, src/pal/pal_bsd.h, src/pal/pal_bsd_aligned.h, src/pal/pal_concept.h, src/pal/pal_freebsd_kernel.h, src/pal/pal_haiku.h, src/pal/pal_linux.h, src/pal/pal_open_enclave.h, src/pal/pal_plain.h, src/pal/pal_posix.h, src/pal/pal_windows.h, src/test/perf/low_memory/low-memory.cc
=> Fully static PALs and simplified inheritance

src/mem/pagemap.h, src/test/func/pagemap/pagemap.cc
The pagemap was double incrementing the index level.  This did not
exhibit in any use case of the pagemap as it only used 0 or 1 level of
intermediate index for all current use cases.
This commit fixes the bug, and adds a test that uses the pagemap in a
different configuration that has multiple levels of intermediate index
node.
=> Fix bug in pagemap when index has many levels

CMakeLists.txt, src/pal/pal.h, src/pal/pal_dragonfly.h
- Close to OpenBSD as there is no malloc*size api nor arbritrary
alignment support.
- Like FreeBSD, MAP_NORESERVE never had been implemented even tough
still present in the header but not mentioned in the man page,
FreeBSD has reserved the value for another later usage seems
DragonFly has just out of sync header.
=> DragonFly support (userland).

CMakeLists.txt
This has been present since 4e1f5829a754ab9c170ec090979d3a670d2d5d1a and resulted in the 16MiB shared library shim using the default 1MiB chunk size.
=> Fix typo in macro definition for 16MiB shared library shim (#253).

src/mem/superslab.h, src/pal/pal_posix.h
Fixes the meta-data initialisation for the superslab in the 16MiB case.
This superseeds #258 as the problem is more general.
=> Superslab bug fix

src/mem/alloc.h, src/mem/allocconfig.h, src/mem/chunkmap.h, src/mem/mediumslab.h
Riding around on a POWER Linux box brings out corner cases.
=> Small fixes from living unusually

src/mem/alloc.h, src/mem/globalalloc.h, src/mem/remoteallocator.h, src/mem/sizeclass.h
Smuggle the size class in Remote objects, so that we can leave Remote pointers bounded to their underlying allocation and yet forward a Remote message using only local state.  That is, we need to avoid going to the {Alloc,Super,Medium,Meta}slab headers unless we're consuming the Remote message back into our free lists.
=> CHERI prep: stave off amplification for Remote routing

src/aal/aal.h, src/aal/aal_sparc.h, src/pal/pal_linux.h, src/pal/pal_open_enclave.h, src/pal/pal_posix.h, src/pal/pal_solaris.h
Also cmpxchg16gb support detection is based on the host but on
a cross compile context it fails to apply properly.
=> Sparc support proposal.

src/mem/chunkmap.h, src/mem/pagemap.h, src/test/func/external_pagemap/external_pagemap.cc
At some point in the refactoring, these were broken.
=> Fix external pagemap usage.

CMakeLists.txt, src/mem/address_space.h, src/mem/allocstats.h, src/mem/largealloc.h, src/pal/pal.h, src/pal/pal_bsd_aligned.h, src/pal/pal_concept.h, src/pal/pal_consts.h, src/pal/pal_noalloc.h, src/test/func/sandbox/sandbox.cc
Summary of changes:
- Add a new PAL that doesn't allocate memory, which can be used with a
memory provider that is pre-initialised with a range of memory.
- Slightly refactor the memory provider class so that it has a narrower
interface with LargeAlloc and is easier to proxy.
- Allow the address space manager and the memory provider to be
initialised with a range of memory.
This may eventually also remove the need for (or, at least, simplify)
the Open Enclave PAL.
=> Fix the sandbox use case and add a test.

src/mem/largealloc.h, src/mem/pool.h
Allow replacing the type of GlobalVirtual at compile time.
Make that type a friend of Pool so that it can allocate things.
=> Small tweaks to make the sandbox mode happy.

src/ds/address.h, src/ds/bits.h, src/ds/helpers.h, src/mem/address_space.h, src/mem/sizeclass.h, src/pal/pal.h, src/pal/pal_bsd_aligned.h, src/pal/pal_freebsd_kernel.h, src/pal/pal_posix.h, src/pal/pal_windows.h
@achamayou can you test if this shows the same regression in Debug performance.
=> Update to use a more efficient power of 2 check.

src/pal/pal_apple.h
The actual code works fine on the usual Mac Intel however, some failures
occurs with some unit tests on the ARM h/w when zero'ing page range.
While at it, using MADV_FREE_REUSABLE which is Darwin's specific but helps
command line tools to report better memory accounting.
=> Mac M1 fix proposal.

src/mem/address_space.h, src/mem/largealloc.h
The initialisation had an awkward sequence that used undefined
behaviour. This fixes this.
=> Remove an undefined behaviour

src/pal/pal_apple.h
work more realibly, in both mono and multi thread contexts.
=> Second batch for Mac M1 (mainly) changes proposal to make the whole

CMakeLists.txt, src/pal/pal_bsd.h
The previous setting applied USE_POSIX_COMMIT_CHECKS to snmalloc if it
was a non-release build.  This caused issues in CCF virtual mode, as it
was being built in RelWithDebInfo.
This commit changes the flag to be applied less, but for tests to always
apply the setting independent of build type.
This means that when snmalloc is being used as a library, it will be
off, unless explicitly requested.
=> Change behaviour of USE_POSIX_COMMIT_CHECKS

src/mem/address_space.h, src/mem/largealloc.h, src/pal/pal_consts.h, src/test/perf/low_memory/low-memory.cc
This makes a separate allocation for the callback object.  This makes
it easier for different callbacks to be used.
=> Make LowMemoryNotification object allocated

src/pal/pal_bsd_aligned.h
=> pal bsd aligned build fix due to the -Wconversion flag, it is expected

src/override/rust.cc
This is needed for the pyoxidizer project to extend allocation to the embedded python interface without the allocation tracking overhead in typical rust interface. This is for issue #289
=> Add rust calls without allocation tracking

src/ds/dllist.h, src/ds/helpers.h
The dllist was able to call delete during a destructor if a template
flag was set.  This flag is never set in snmalloc, and was included
to enable reuse in another project.  This was triggering an error on
older mac builds.
This PR calls a templated function when the DLList is destructed.  Hence
other projects can specify the `delete` behaviour if required.
=> Fix for Mac OS X 10.14

src/ds/cdllist.h, src/mem/alloc.h, src/mem/metaslab.h, src/mem/slab.h, src/mem/superslab.h
The link object was previously stored in a disused object.  This is
good for reducing meta-data, but if we want to reduce the meta-data
corruption potential, then this is not a good design choice.
This commit moves it into the Metaslab.
The overall change improves performance slightly in a couple of cases.
=> Move link out of object space.

src/ds/helpers.h, src/mem/alloc.h, src/mem/metaslab.h, src/mem/sizeclass.h, src/mem/sizeclasstable.h, src/test/func/memory/memory.cc, src/test/func/release-rounding/rounding.cc
The previous reciprocal division branch on the prime that the sizeclass
was constructed from. All sizeclasses can be represented as
2^n * {1,3,5,7}
This lead to a very small table, but some work to calculate the
appropriate shifts and multiplications to implement reciprocal division.
This commit uses a completely uniform representation for every
sizeclass using a lookup table.  Due to the precise ranges that we query
the modulus and rounding on, we can do this much more efficiently.
The func-release-rounding exhaustively tests all the queries we are
interested in.
=> Better reciprocal division and modulus.

src/mem/metaslab.h, src/mem/sizeclass.h, src/mem/sizeclasstable.h, src/mem/slab.h, src/mem/superslab.h
The metaslab contains a field specifying how many elements have been
allocated.  As the code has evolved this field has now always become
the maximum capacity of the slab for the sizeclass.
This commit looks up this value based on the sizeclass, and removes the
field from the slab's metadata.
=> Remove allocated field from Metaslab

src/mem/slab.h, src/mem/superslab.h, src/test/measuretime.h, src/test/perf/contention/contention.cc, src/test/perf/external_pointer/externalpointer.cc, src/test/perf/low_memory/low-memory.cc, src/test/perf/singlethread/singlethread.cc
If the metadata is made larger, then the calculation of which classes can use the "short slab" was incorrect.  In particular, if the meta data grows above half the size of a slab, then things go very wrong.  This alters that calculation.
=> Bug fix for superslab meta-data

CMakeLists.txt, src/mem/alloc.h, src/mem/freelist.h, src/mem/metaslab.h, src/mem/slab.h, src/mem/superslab.h
The slab allocation pattern is randomised based on the deallocation
pattern.  This achieved by using two queues to enqueue free elements
onto.  We pick "randomly", which queue to add to, and then when we take
the free_queue to use, we splice the two queues together.
The PR also enables tests for the Checked code.
=> Randomise slab allocation pattern

src/mem/freelist.h, src/mem/metaslab.h, src/mem/slab.h, src/mem/superslab.h
When a slab has been fully allocated, then we no longer
check it has entries until something returns an allocation to this slab.
However, it is possible that only a single allocation is available, and
then we can end up frequently on the slow path.
This change only considers free lists that cover at least 1/8 of a slab.
This means that we will hit the slow path less frequently.  This also
means that the randomisation changes will have more entropy: with a
single element free list there is only one order.
For large small sizes it can still be a single element, as 1/8 is of the
slab capacity is below 1.
=> Threshold freelist wakeup

src/ds/bits.h, src/mem/entropy.h, src/mem/freelist.h, src/mem/metaslab.h, src/mem/sizeclasstable.h, src/mem/slab.h, src/test/func/bits/bits.cc
This PR implements the full randomisation of a small slab of allocations.  This uses an algorithm to build a random cycle in a slab, and then encodes that into the free list.  This provides a lot of entropy in the layout within a slab. 
The PR also refactors the FreeListBuilder, so it can be more compact and not introduce randomisation. This PR reestablishes the non-CHECK_CLIENT performance that was impacted by some of the randomisation code in previous PRs.
=> Further Randomisation

docs/StrictProvenance.md, src/aal/aal.h, src/aal/aal_concept.h, src/ds/address.h, src/ds/ptrwrap.h, src/mem/address_space.h, src/mem/alloc.h, src/mem/arenamap.h, src/mem/chunkmap.h, src/mem/freelist.h, src/mem/largealloc.h, src/mem/mediumslab.h, src/mem/metaslab.h, src/mem/pool.h, src/mem/ptrhelpers.h, src/mem/remoteallocator.h, src/mem/sizeclass.h, src/mem/slab.h, src/mem/superslab.h, src/pal/pal.h, src/pal/pal_concept.h, src/test/func/fixed_region/fixed_region.cc, src/test/func/sandbox/sandbox.cc, src/test/func/two_alloc_types/main.cc
Take.. I dunno, five? six?  This supersedes #267.  I have not yet actually seen this version through to completion -- that is, I haven't glued the CHERI AAL and CheriBSD PAL onto it, yet, but it's been sufficiently slow going that I don't want to delay any longer before getting initial reviews.
The most salient feature is that there's just one pointer wrapper type, now.  An `AuthPtr<T, bounds>` points at `T` and has an indicated static approximation of its bounds.  Those come in several flavours: arena (awesome power, use carefully), slab (generally 1M or 16M chunks, but perhaps larger as part of large allocations), and alloc (a single allocation), and additionally carry indication of whether the `VMMAP` permission has been stripped (more generally, any "platform constraints" the PAL …
=> 202103 CHERI prep plumbing

src/pal/pal_netbsd.h
getentropy not being guarded, providing prototype even tough we end up
using the C++ api version.
=> netbsd build fix.

src/mem/alloc.h, src/test/func/memory/memory.cc
The CapPtr refactoring was largely compiler guided; unfortunately, it turns out
that the static-sized alloc function is not well exercised.  As such, some type
errors and unnecessary unsafety lurked behind missing template instantiation.
Correct those and add calls to the test harness to make sure we always generate
at least one instance of each small/medium/large case.  While here, it doesn't
hurt to make sure that we call all three possible dealloc() flavors as well.
This will, if nothing else, force instantiation of the static-sized dealloc
template as well.
=> Fix static-sized alloc paths, add compilation test

CMakeLists.txt, azure-pipelines.yml, src/mem/alloc.h, src/mem/allocslab.h, src/mem/freelist.h, src/mem/globalalloc.h, src/mem/metaslab.h, src/mem/remoteallocator.h, src/mem/sizeclass.h, src/mem/sizeclasstable.h
The remote deallocation next pointers are not protected in the same way that free list pointers are. This PR provides refactorings to make it easier to add those changes.
=> Refactorings for encoding remote deallocation next pointers

src/ds/aba.h
This method is used in the Verona SPMCQ.
=> Add init method to ABA on ARM

CMakeLists.txt, src/pal/pal.h, src/pal/pal_apple.h, src/pal/pal_consts.h
This is a rewrite of the Apple PAL that implements the `AlignedAllocation`, `Entropy`, and `LazyCommit` features through native Apple APIs.
It adds a dependency on `Security.framework` via `SecRandomCopyBytes`. Apple actively discourages use of `getentropy` and the symbol is [not allowed on the App Store](https://developer.apple.com/forums/thread/675396).
I removed support for `USE_POSIX_COMMIT_CHECKS` because the POSIX memory management APIs are no longer used but I'd like to avoid a regression. I need some context about what the `memset` and `mprotect` calls in `pal_bsd.h` and `pal_posix.h` are supposed to accomplish. Is it supposed to emulate Windows' decommit behavior? If so, why do the pages need to be decommitted? What are the invariants?
I hope to use the mach APIs to implement the …
=> Rewrite Apple PAL using native APIs

src/ds/helpers.h
Extended the TrivialInitAtomic interface with exchange and fetch_add.
These are not used by snmalloc itself, but can be used by downstream projects which use the helpers.
For fetch_add I tried to keep the error messages for non-integral types as readable as possible without having to do a full template instantiation:
-fetch_add(integral_type) will give and error "no member named 'fetch_add' in 'std::__1::atomic<template_type>'"
-fetch_add(non_integral_type) will give and error "no matching member function for call to 'fetch_add'"
@nwf @mjp41 Does this make sense for an extension and is this correct C++?
=> Extended TrivialInitAtomic

src/mem/threadalloc.h
GCC is a lot more picky about extern "C" definitions in namespaces than
clang and so the `friend` declaration wasn't picked up by the version of
the function declared in the `snmalloc` namespace.  Move it out to where
GCC is happy with it.
=> Fix the build with GCC and libc cleanup.

src/ds/aba.h
The check relies on a thread_local variable which might not be available when using SlowAllocator on custom platforms.
=> Allow disabling the Debug-mode check in the ABA code

src/backend/pagemap.h
This dramatically improves the runtime of at least `perf-external_pointer` tests, which call `get` with `potentially_out_of_range = true` quite a lot, at least on my Linux box.
=> pagemap: don't eagerly commit on LazyCommit PALs

src/mem/fixedglobalconfig.h, src/pal/pal.h, src/pal/pal_noalloc.h, src/pal/pal_open_enclave.h, src/test/func/fixed_region/fixed_region.cc, src/test/func/two_alloc_types/alloc1.cc
PalNoAlloc forwards the Entropy setting of the underlying PAL as well as using its zeroing function.
Removed the unused parts of the PalOpenEnclave after the refactor.
`PalOpenEnclave::setup_initial_range` should be replace by:
`snmalloc::FixedGlobals fixed_handle;
fixed_handle.init(snmalloc::CapPtr<void, snmalloc::CBChunk>(heap_start), heap_size);`
=> Improved OEPal integration with the new snmalloc architecture

src/mem/corealloc.h, src/mem/freelist.h
This encodes a back pointer in each node.  The back pointer is stored
in an encoded form so that it is hard to corrupt and trick the allocator
into following incorrect pointers.
This changes the encoding from previously being a Feistel network on
the next pointer that was using the prev as part of the key, to now
effectively using a doubly linked queue, where the back pointers are
scrambled, so it is hard to forge them.
This has the positive effects of
- Not needing to store previous while building the list, as the append
nows, curr and next at the point of writing into next, and does not
need an additional previous.
- The encoding is not affecting the actual next value, so more
instructions can be executed in parallel by the CPU.
Future extensions, store a changing key in the …
=> Cleaner implementation of signed pointers.

src/mem/entropy.h
Including <entropy> brings in <iostream>, which breaks the in-libc
build.
=> Don't depend on <entropy> if we don't need it.

src/ds/address.h, src/mem/metaslab.h
It is UB to offset from `nullptr` (except perhaps with a 0 offset).  Apparently clang is able to use this to reason, given `void* p`, that comparing `__builtin_align_down(p, x)` against `handle.fake_large_remote` (i.e., a `static inline constexpr` `nullptr`) must be the same as comparing `p` itself against `nullptr`.
In `MetaEntry`'s constructor, converting the provided `RemoteAllocator*` to `uintptr_t` before offsetting avoids the UB.  (While here, don't use `address_cast()`, as `address_t` will, on CHERI, be `ptraddr_t` and not `uintptr_t`.)
Doing the alignment in `get_remote` at `uintptr_t` before casting to `RemoteAllocator*`, rather than converting and then aligning, prevents the reasoning above from eliminating the alignment.
=> MetaEntry vs nullptr UB

CMakeLists.txt, ci/scripts/test.sh, docs/PORTING.md, src/backend/address_space.h, src/backend/backend.h, src/backend/pagemap.h, src/ds/address.h, src/ds/defines.h, src/ds/helpers.h, src/mem/allocconfig.h, src/mem/corealloc.h, src/mem/entropy.h, src/mem/fixedglobalconfig.h, src/mem/freelist.h, src/mem/metaslab.h, src/mem/pool.h, src/mem/sizeclasstable.h, src/pal/pal_apple.h, src/pal/pal_bsd.h, src/pal/pal_bsd_aligned.h, src/pal/pal_concept.h, src/pal/pal_posix.h, src/pal/pal_windows.h, src/test/func/fixed_region/fixed_region.cc, src/test/func/pagemap/pagemap.cc, src/test/func/two_alloc_types/alloc1.cc, src/test/perf/external_pointer/externalpointer.cc
The primary aim of this PR is to be able to enforce the invariant that all memory in the address space manager has committed pages for the corresponding entries in the pagemap.  This will improve windows support, and enable turning off pages inside the pagemap that are no currently required. 
To support this, I have made all Pals that perform allocation provide `reserve_at_least`.
=> Refactor pagemap and ASM relationship

src/backend/backend.h, src/mem/metaslab.h, src/mem/pool.h, src/test/func/fixed_region/fixed_region.cc, src/test/setup.h
The meta-data in the `CHECK_CLIENT` mode is allocated from its own areas,
where most of the pages have been disabled, and the location within this
range is randomised.
This protects from trivial OOB read/write hitting the meta-data.
More complex controlled offsets are also mitigated due to the sparse
level of pages being turned on (i.e. not `PROT_NONE`).
=> Add protection to meta-data

src/mem/threadalloc.h, src/override/malloc.cc, src/snmalloc.h, src/snmalloc_core.h, src/test/func/fixed_region/fixed_region.cc, src/test/func/thread_alloc_external/thread_alloc_external.cc
This reduces the number of places that `globalconfig.h` is compiled to add building alternative backends.
=> Remove globalconfig.h includes.

src/mem/remoteallocator.h
Take the maximum of...
* CACHELINE_SIZE (for performance)
* next_pow2(NUM_SIZECLASSES + 1) so that, when the pagemap points to a Remote,
the (small) size class stuffed in the bottom bits can be removed by alignment
* next_pow2(NUM_LARGE_CLASSES + 1) so that, when the pagemap isn't pointing to
a Remote, when the associated chunk is (part of) a large allocation, aligning
the Remote* results in 0.
The last of these conditions will almost never be the deciding factor, as there
are generally many more small size classes than large ones, but it shouldn't
hurt to be safe.
=> Correct REMOTE_MIN_ALIGN

src/backend/address_space.h, src/backend/address_space_core.h, src/backend/backend.h
The address space manager uses the pagemap entry to form linked lists of
unused address space above MIN_CHUNK_SIZE.  It continues to use
references in the block below that threshold.
In the CHECK_CLIENT mode this makes it hard to corrupt the ASM as only
meta-data uses allocations below MIN_CHUNK_SIZE from the ASM. This
allocations will be protected with guard pages by the backend.
=> Make address space manager use pagemap for next pointers

src/ds/defines.h, src/mem/corealloc.h, src/mem/entropy.h, src/mem/freelist.h, src/mem/globalconfig.h, src/mem/localcache.h, src/mem/metaslab.h, src/mem/remoteallocator.h, src/mem/remotecache.h
This commit adds a simple XOR encoding to the next_object pointer in
FreeObjects.  This removes the trivial way of getting hold of a physical
address from the system by observing the free list pointers in
deallocated objects.
=> XOR encoded next_object

.github/workflows/main.yml
The naming is more than a little confusing.  AIUI, in Ubuntu's terminology, the
`powerpc` packages are for 32-bit machines, the `ppc64-powerpc` packages are for
Big Endian 64-bit machines, and the `ppc64el` packages are for Little Endian
64-bit machines.
Everyone seems to have agreed that the long-term answer for 64-bit PowerPC is
Little Endian (Debian maintains an unofficial BE port, but Canonical/Ubuntu,
RedHat, and SUSE all seem to have standardized on LE).
For maximal confusion, the appropriate triple's first component is, however,
`powerpc64le`.
=> Add cross CI for Ubuntu powerpc64el

.github/workflows/main.yml, src/ds/defines.h, src/mem/pagemap.h
Also add a check that the test programs are under about ten megabytes
(they're currently around one on platforms that put inline statics full
of zeroes into BSS and around 270 on ones that don't).
Fixes #339
=> Force global pagemaps into BSS

.github/workflows/main.yml
Use a matrix containing objects rather than a matrix containing keys
that we try to use to define arrays of things.
Fix a typo in ARCH.  Too much Arm made it AARCH.
=> Clean up QEMU CI

src/backend/backend.h
This change is to enable code reuse when implementing a custom BackendAllocator, by enabling inheritance from it and its GlobalState.
Changes field protection from private to protected within GlobalState and templates the actual type of the Pagemap entries, with a default to MetaEntry.
Valid template arguments for the Pagemap entries should be able to seamlessly convert to and from MetaEntry and have a size that is a power of 2.
=> Allowing GlobalState to be extended easier for custom Backend implementations

src/backend/pagemap.h
Given a const reference to an entry in the Pagemap (as the one returned by get), return the base address of the range it corresponds to.
=> Added the ability to perform a reverse lookup in the Pagemap

src/mem/sizeclasstable.h
The threshold for waking is used to ensure that we only use a slab when
it has sufficient space that we won't hit the slow path to soon after
using this slab. In the checked version, this is also used to give some
entropy in layout.  Changing this to always be a pertcentage in the
checked case increases the effectiveness of the free list to detect OOB
write.
=> Make threshold for waking always a percentage

src/ds/helpers.h, src/mem/corealloc.h, src/mem/globalalloc.h, src/mem/localalloc.h, src/mem/pool.h, src/mem/pooled.h, src/mem/threadalloc.h, src/test/func/pool/pool.cc
The primary change is to allow a generic usage of the Pool type, which does not just get its pool state from the SharedStateHandle (this being necessary for the pool of allocators). The SharedStateHandle template parameter is promoted to the class as all methods need it. Also the Pool class now takes a function as parameter which is the accessor to the pool state. There is a helper class to create a singleton global pool state for arbitrary types.
For ease of use I have also added an alias AllocPool<typename SharedStateHandle> for the allocator pool.
If people agree with the overall design, then I will add a test for this functionality.
An additional small change is to delete the copy constructor and copy assignment operator for LocalAllocator. This is to avoid the misuse of the …
=> Changes to integrate snmalloc2 into Verona

src/test/opt.h
Enables more options for writing tests and Opt should not be modifying argv content anyway.
=> Added constness to argv in Opt

src/backend/backend.h
With this change a new BackendAllocator implementation can just use the AddressSpaceAllocatorCommon and not have to inherit from BackendAllocator.
=> Extracted the core elements of the BackendAllocator into a common helper

.github/workflows/main.yml, CMakeLists.txt, src/backend/commonconfig.h, src/backend/pagemap.h, src/ds/address.h, src/ds/defines.h, src/mem/localalloc.h, src/override/malloc.cc, src/override/memcpy.cc, src/override/override.h, src/pal/pal_posix.h, src/test/func/memcpy/func-memcpy.cc
The memcpy implementation is not completely stupid but is almost
certainly not as good as a carefully tuned and optimised one.
Building snmalloc with FreeBSD's libc memcpy + jemalloc and with this,
each 10 times, does not show a statistically significant performance
difference at 95% confidence.  The snmalloc version has very slightly
lower median and worst-case times.  This is in no way a sensible
benchmark, but it serves as a smoke test for significant performance
regressions.
The CI self-host job now uses the checked memcpy.
This also fixes an off-by-one error in the external bounds.  This is
triggered by ninja, so we will see breakage in CI if it is reintroduced.
In debug builds, we provide a verbose error containing the address of
the allocation, the base and bounds of the …
=> Add memcpy with bounds checks.

src/aal/aal.h, src/aal/aal_concept.h, src/backend/pagemap.h, src/ds/bits.h, src/mem/sizeclasstable.h, src/mem/slaballocator.h, src/pal/pal_concept.h, src/pal/pal_noalloc.h, src/pal/pal_posix.h, src/pal/pal_windows.h, src/test/func/memory/memory.cc, src/test/perf/external_pointer/externalpointer.cc
FreeBSD RISC-V is the primary motivating example of a platform that really constrains the AS: it exposes a 38 bit AS for user programs (that is, it uses the sv39 page table format and cleaves the AS in half for kernel/user).  If we go with the traditionally hard-coded 48 bit AS estimate from `ds/bits`, we end up trying to allocate the whole user AS (48 bits in AS - 14 bits for a 16K chunk size + 4 bits for a `MetaEntry` = 38 bits of `Pagemap`).  As you might imagine, this doesn't go well for us (and it goes somehow even worse for us on CHERI when we ask for a 39-bit AS allocation...).  FreeBSD MIPS is similar and exposes a 39 bit AS and so also suffers (even if we only ask for half the AS for the Pagemap, it still doesn't really work out well for us), but I don't think that matters as …
=> Move bits/address_bits to AAL/PAL

src/mem/entropy.h, src/mem/freelist.h, src/mem/remoteallocator.h
* Add extra key to freelist.  This follows the encoding Cedric suggested
for a signature of two things. Free list key now has a pair of keys
for encoding previous pointer. This makes it harder to extract the
underlying keys out of the multiplication.
* Apply SFINAE to the extract_segment.
=> Tidy TODOs from Free List

docs/PORTING.md, src/backend/pagemap.h, src/pal/pal_apple.h, src/pal/pal_bsd.h, src/pal/pal_bsd_aligned.h, src/pal/pal_consts.h, src/pal/pal_freebsd_kernel.h, src/pal/pal_posix.h, src/pal/pal_windows.h
This exposes a readonly notify using, so that the underlying platform
can map the range of pages readonly into the application.  This improves
performance of external pointer on platforms that support lazy commit
of pages as it can access anything in the range.
=> Expose notify_using_readonly

src/ds/address.h
It doesn't modify the objects and this avoids a const_cast in callers
that have a const pointer.
=> Make pointer_diff take const pointers.

src/aal/aal_arm.h
Use the "C" inline assembler constraint for capability registers on
Morello.
This gets us building and running on Morello.  Sorry to have overlooked it in #402.
=> ARM AAL support for Morello

src/backend/address_space_core.h, src/mem/allocconfig.h, src/mem/allocstats.h, src/mem/chunkallocator.h, src/mem/corealloc.h, src/mem/localalloc.h, src/mem/localcache.h, src/mem/metaslab.h, src/mem/remoteallocator.h, src/mem/remotecache.h, src/mem/sizeclasstable.h, src/override/memcpy.cc, src/override/rust.cc, src/test/func/first_operation/first_operation.cc, src/test/func/malloc/malloc.cc, src/test/func/memory/memory.cc, src/test/func/release-rounding/rounding.cc, src/test/func/sizeclass/sizeclass.cc, src/test/func/teardown/teardown.cc
The primary aim for this refactor is to use a representation for
sizeclasses that uniformly covers both large and small.  This allows
certain operations such as alloc_size and external_pointer to be
uniformly implemented.
The additional types make clear which kind of sizeclass is in use.
This also tidies up the code for sizeclass based divisible by and
modulus.
It fixes a bug in rust_realloc that didn't correctly determine a realloc
was required for large classes.
=> Refactor use of sizeclasses

src/backend/pagemap.h, src/ds/defines.h, src/ds/helpers.h, src/ds/spmcstack.h, src/mem/corealloc.h, src/mem/localalloc.h, src/mem/localcache.h, src/mem/remoteallocator.h, src/override/malloc.cc, src/override/memcpy.cc, src/pal/pal_apple.h
Consider `-Werror -Wall -Wextra`:
In another project's `common.h`:
```
#define likely 
#define unlikely
```
then
```
#include <common.h>
#include <snmalloc.h>
```
will give errors
=> put likely/unlikely in scope

src/backend/address_space_core.h, src/ds/defines.h, src/mem/allocstats.h, src/mem/globalalloc.h, src/override/memcpy.cc, src/pal/pal_noalloc.h, src/pal/pal_plain.h, src/pal/pal_posix.h, src/test/func/bits/bits.cc, src/test/func/memory/memory.cc, src/test/func/pagemap/pagemap.cc, src/test/func/pool/pool.cc, src/test/func/two_alloc_types/main.cc, src/test/setup.h
This PR makes `UNUSED` as a function marked by `[[maybe_unused]]`. This enables us to put `UNUSED` to namespace without pollute global macros.
=> clean up unused usages

src/ds/seqset.h, src/mem/corealloc.h, src/mem/freelist.h
If there is only one slab remaining, then we probabalisticly allocator a
new one. If a slab is barely in use, then this could cause us to
effectively double the number of slabs in use.
This commit checks if the remaining slab has enough remaining elements
to provide randomisation.
=> Modify heuristic for adding new slabs.

src/mem/threadalloc.h
build error due to access none attribute on the pthread_setspecific's
value argumenti (glibc).
=> build fix proposal for GCC 11.x (spotted with 11.2.0).

.github/workflows/main.yml
Windows can hang due to assert failures in CI.  Add a timeout to get
some information of what is happening.
=> Add timeout to ci tests.

docs/StrictProvenance.md, src/aal/aal_cheri.h, src/backend/address_space_core.h, src/mem/localalloc.h, src/pal/pal_freebsd.h
* Updates the documentation on `StrictProvenance`
* fixes a test suite crash (unsure what changed; fix might not be exactly the right shape)
* moves to using the base of the provided capability rather than the cursor in `dealloc` (should we do the same for `external_pointer`)?
* adds a missed bounds setting in the address space core.  We might wish to refine the spatial `CapPtr` dimension to differentiate between chunks within the address space manager and chunks as handed out, but I haven't tried actually doing that to see if it works.
Opinions more than welcome.
=> 2021/11 CHERI followup

src/mem/localalloc.h
c299826f582d991a480ac87a608e6c391b5c3437 landed as part of #428 while #416 was
still outstanding and not all conflicts are textual.  Sorry!
=> That's snmalloc_check_client to you.

src/mem/corealloc.h, src/mem/localalloc.h, src/mem/localcache.h, src/mem/metaslab.h, src/mem/sizeclasstable.h, src/test/func/release-rounding/rounding.cc
This change sets all large allocations to be owned by the originating
thread. This means they will be messaged back to the original thread
before they can be reused.
The following reason for making this change:
* This will improve producer/consumer apps involving large allocations.
* It enables the implementation of a more complex chunk allocator that
reassembles chunks.
* It addresses an issue with compartmentalisation where the handling of
large allocations can result in meta-data ownership changing.
=> Post large deallocations to original thread

src/pal/pal_linux.h, src/pal/pal_netbsd.h, src/pal/pal_posix.h
std::random_device seems unimplemented on this platform
thus falling back to the usual /dev/urandom device for
the time being.
=> PAL netbsd (temporary until some time 2022) build fix.

src/backend/address_space_core.h, src/backend/commonconfig.h, src/mem/localalloc.h
Since #441 was merged, pagemap entries are no longer ever set to
fake_large_remote.
=> Remove fake_large_remote

src/mem/sizeclasstable.h, src/override/memcpy.cc, src/test/func/memcpy/func-memcpy.cc, src/test/measuretime.h, src/test/perf/memcpy/memcpy.cc
One optimisations and some perf testing for guarded memcpy.
The optimisation is a to use a slightly different reciprocal division/modulus calculation, so that large allocations can be a degenerate case.
=> Optimise guarded memcpy

src/backend/backend.h, src/backend/pagemap.h, src/mem/localalloc.h, src/override/memcpy.cc, src/test/perf/memcpy/memcpy.cc
There was a slightly awkward jump in the guarded memcpy implementation were if it was uninitialised, it then used the address of the default value.  This commit lifts some of the initialisation checking up a few levels, so that it can be detected, and we just succeed the bounds check if snmalloc has not been initialised.
The resulting ASM is:
```asm x86
<memcpy_guarded>:
mov    rax,QWORD PTR [rip+0xbfa]        # Load Chunk map base
test   rax,rax                          # Check if chunk map is initialised
je     DONE                             #  |
mov    rcx,rdi                          # Get chunk map entry
shr    rcx,0xa                          #  |
and    rcx,0xfffffffffffffff0           #  |
mov    rax,QWORD PTR [rax+rcx*1+0x8]    # Load sizeclass
and    eax,0x7f …
```
=> Improve check_bounds init check.

src/ds/defines.h, src/mem/threadalloc.h, src/override/malloc.cc, src/test/func/malloc/malloc.cc
- Mark the hook that we're exporting for the threading library to call
to clean up per-thread malloc state as 'used'.  It was changed to
`inline` to allow duplicate copies of it to be merged but this also
means that it isn't emitted at all in compilation units that don't
use it (and it isn't used internally at all).
- Fix the __je_bootstrap_* functions, which are used to bootstrap TLS
allocation, for the changes to ScopedAllocator.
=> Small fixes for snmalloc used in FreeBSD libc.

src/backend/address_space_core.h, src/test/func/malloc/malloc.cc
Add check in malloc test that CHERI capability length matches `alloc_size` and fix a bug in `address_space_core.h` were not being set correctly.
=> CHERI bounds bug

src/ds/helpers.h, src/mem/bounds_checks.h, src/mem/chunkallocator.h, src/override/memcpy.cc, src/pal/pal.h, src/test/func/malloc/malloc.cc
This introduces a very limited formatter that can embed strings and hex
representations of pointers / integers in an internal buffer. This is
used to format error strings for passing to `Pal::error`.  This is used,
in turn, by a wrapper for reporting bounds checks, which can be used by
external functions to implement bounds checks.
This removes the sprintf_l usage from the bounds checks.
This provides enough of a format implementation that the tests
introduced in #465 can be refactored to use this, instead of their
custom `printf` wrapper and that can be used by SNMALLOC_CHECK.  This
will be a follow-on PR.
=> Refactor error reporting for bounds checks.

src/ds/defines.h, src/ds/helpers.h, src/pal/pal.h, src/test/func/jemalloc/jemalloc.cc, src/test/func/malloc/malloc.cc, src/test/func/memcpy/func-memcpy.cc, src/test/helpers.h
- Refactor the existing SNMALLOC_ASSERT and SNMALLOC_CHECK.  These now
use the FatalErrorBuilder to format the output if a format string is
provided.
- Extend the FatalErrorBuilder to print decimal integers for signed
values.
- Rewrite the macros used in the jemalloc tests to use
FatalErrorBuilder and move them into a header.
- Refactor some of the tests to use the new macros.
=> Add test helper macros.

CMakeLists.txt
disable purposely --no-undefined for this platform.
=> shared lib linkage build fix for OpenBSD.

src/override/memcpy.cc
This now either outperforms, or performs as well within the region of
measurement noise as, FreeBSD's libc memcpy, which is hand-written
assembly.
The checked version still incurs a noticeable overhead.
=> Improve the `memcpy` implementation.

src/pal/pal_freebsd_kernel.h, src/pal/pal_noalloc.h, src/pal/pal_posix.h, src/pal/pal_windows.h, src/test/helpers.h, src/test/setup.h
This provides a single place for reporting messages to the user.
While here, be consistent about using stderr for things that should go
to stderr.  We were previously using a mix of stderr and stdout.
=> Add Pal::message.

src/pal/pal_bsd_aligned.h, src/pal/pal_freebsd.h, src/pal/pal_posix.h
We currently include 256+GiB zeroes in core dumps.  This is a QoI issue
because it causes core dumps to take a long time (even if ZFS is able to
compress large runs of zeros down to almost nothing, they still take a
long time to load into debuggers).  This patch removes anything marked
as not-using or using-but-read-only (pagemap zero pages) as excluded
from core dumps.
Adding __builtin_trap() to the end of `func-malloc-fast` now gives a 21
MiB core dump rather than a 256 GiB one.
=> [FreeBSD] Exclude unused memory from core dumps.

src/pal/pal_freebsd.h
You can't or together multiple `madvise` flags in a single call.
=> `madvise` arguments are not flags.

src/test/func/memory/memory.cc
test_random_allocation, g++ sees the removal from the list of the test case
as UAF.
=> g++ 12 unit test build fix.

src/backend/largebuddyrange.h, src/backend/pagemap.h, src/ds/address.h, src/ds/ptrwrap.h, src/mem/freelist.h, src/mem/metaslab.h, src/test/func/external_pagemap/external_pagemap.cc, src/test/func/malloc/malloc.cc, src/test/func/memcpy/func-memcpy.cc, src/test/perf/memcpy/memcpy.cc
After utter silence from the compiler as part of #477 spooked both @mjp41 and me (everything was fine, but it really should have been a warning), here's something that tries to induce the compiler to speak up a little more should similar things happen again.
=> unsafe_{to,from}_uintptr<T> and a quick audit of casts

CMakeLists.txt
The /DEBUG is a linker flag and not a "compile_option".
=> Fix Debug symbols for Windows CI.

docs/AddressSpace.md, src/backend/backend.h, src/backend/backend_concept.h, src/backend/chunkallocator.h, src/backend/largebuddyrange.h, src/backend/metatypes.h, src/mem/corealloc.h, src/mem/localalloc.h, src/mem/metaslab.h, src/mem/remoteallocator.h, src/mem/remotecache.h, src/mem/sizeclasstable.h, src/test/func/memory/memory.cc
This is starting to sprawl a bit, but it's all sort of thematically related towards the end goal of removing includes of src/mem from src/backend.
By and large NFCI, except for "clobber MetaEntry-s in dealloc_chunk", which more aggressively zeros out `MetaEntry::meta` pointers and came up while writing docs.
=> Further disentangle front- and back-ends

src/backend/backend.h, src/backend/backend_concept.h, src/mem/corealloc.h, src/mem/localalloc.h, src/mem/metaslab.h, src/mem/remotecache.h
David points out that the downcasts I had introduced were UB.  Instead, go back
to passing MetaEntry-s around and make MetaslabMetaEntry just a namespace of
static methods.
This partially reverts 7940fee00cf0ce43c3c40584a3b3e4fb8d77cfd8
=> Stop playing OO games with MetaEntry

src/backend/metatypes.h
C++ has no way of exposing it only to things that are backend
implementations.  Eventually this class should be made purely part of
the CHERI back end.
=> Make MetaCommon state public.

src/pal/pal_bsd.h, src/pal/pal_bsd_aligned.h, src/pal/pal_freebsd.h, src/pal/pal_posix.h
On FreeBSD (possibly elsewhere) the normal versions of these go via an
indirection layer because they are pthread cancellation points.  This
indirection layer does not work correctly if pthreads can't allocate
memory and so we can't get debug output until malloc is working, at
least a little bit.
With this version, we can call the __sys_ variants, which skip any libc
/ libthr interposition.
=> Allow POSIX PALs to overwrite writev and fsync.

src/snmalloc/backend/backend.h, src/snmalloc/backend_helpers/commitrange.h, src/snmalloc/backend_helpers/empty_range.h, src/snmalloc/backend_helpers/globalrange.h, src/snmalloc/backend_helpers/largebuddyrange.h, src/snmalloc/backend_helpers/pagemapregisterrange.h, src/snmalloc/backend_helpers/palrange.h, src/snmalloc/backend_helpers/smallbuddyrange.h, src/snmalloc/backend_helpers/statsrange.h, src/snmalloc/backend_helpers/subrange.h
This doesn't give any extra flexibility: the range itself can be either
a stateless class, a class with no per-instance state that stores all of
static fields, or a class with stateful instances.  It did add a
requirement that every range implementation added an indirection layer.
Removing this removes over 100LoC with no loss of functionality.
=> Remove indirection of state in ranges.

src/snmalloc/mem/corealloc.h, src/snmalloc/mem/freelist.h
Clang 15 doesn't build the release builds with CHECK_CLIENT enabled
because they are using `SNMALLOC_ASSERT` and so the values that we're
collecting to check are never actually checked.  This is probably a bug
- if we're turning on the checks, I imagine it's because we want them.
=> Check things in release builds with check-client.

src/snmalloc/backend/fixedglobalconfig.h, src/snmalloc/backend_helpers/commonconfig.h, src/snmalloc/mem/backend_wrappers.h, src/test/func/domestication/domestication.cc
This refactoring was provided by David.  Previously if a backend
provided a capptr_domesticate function with the wrong type it would be
silently ignored.  This change requires backends to explicitly opt in
to domestication via a new Backend::Option and ensures the compiler
will loudly complain if there is a mismatch.
=> Refactor capptr_domesticate SFINAE to make more statically safe.

src/snmalloc/backend/backend.h, src/snmalloc/backend_helpers/largebuddyrange.h
Modify the large buddy allocator to gradually grow its refill size up to a set amount.  This is designed to work well on more limited address space platforms, but be able to grow to reduce contention on larger systems.
Primary use is for OE, where changes from CoffeeLake to IceLake mean the address space limits are very different.
=> Refill heuristic

src/snmalloc/mem/backend_wrappers.h
Note that the second one was incorrect.
=> Simplify asserts introduced in #512.

CMakeLists.txt
Build three levels of checking
- None
- Checks memcpy only
- Checks (full)
Currently you can build checks without enabling the memcpy protection.
This PR fixes that.
=> Enable memcpy checks for check shim

CMakeLists.txt, src/snmalloc/backend/backend.h
The Metadata range should not be shared with the object range.  This
change ensures that their are separate requests to the Pal for meta-data
and object data ranges.  The requests are never combined, and thus
memory cannot flow from being used in malloc to later be used in meta-
data.
=> Modified Metadata range to have separate pool

src/snmalloc/mem/corealloc.h
Currently a failing debug_check_empty does not provide any information.
This change allows it to print the size of the one of the allocations
that has not been freed.
=> debug_check_empty

src/snmalloc/ds_core/defines.h, src/snmalloc/mem/localalloc.h, src/snmalloc/mem/sizeclasstable.h
Some secure allocators check that the C++ supplied size is correct
relative to the meta-data. This adds a check to the secure version of
snmalloc to do that.
=> Check size is correct if specified

CMakeLists.txt, src/snmalloc/global/bounds_checks.h, src/snmalloc/global/memcpy.h, src/test/perf/memcpy/memcpy.cc
This commit changes the codegen for error messages for failed memcpys.
This no longer generates a stack frame and correctly tail calls the
error messages generator.
It also turns the error messages on in Release builds.  This will lead
to better adoption experience.
=> Alter FailFast behaviour of memcpy

src/snmalloc/backend_helpers/commitrange.h, src/snmalloc/backend_helpers/globalrange.h, src/snmalloc/backend_helpers/largebuddyrange.h, src/snmalloc/backend_helpers/logrange.h, src/snmalloc/backend_helpers/pagemapregisterrange.h, src/snmalloc/backend_helpers/range_helpers.h, src/snmalloc/backend_helpers/smallbuddyrange.h, src/snmalloc/backend_helpers/statsrange.h, src/snmalloc/backend_helpers/subrange.h
This exposes a feature on Ranges to access ranges higher up the
stack of ranges.  This could be useful for applying operations in the
middle of a pipeline like
```C++
object_range.ancestor<SpecialRange>().init(...);
```
This allows some initialisation to be added to the middle of pipeline
without breaking the current coding pattern.
It also allows for bypassing some ranges
```C++
object_range.ancestor<LargeObjectsRange>().alloc_chunk(...);
```
Neither are done in this commit, but both will occur in future commits.
=> Enable accessing parent ranges.

src/snmalloc/backend/meta_protected_range.h, src/snmalloc/backend/standard_range.h, src/snmalloc/backend_helpers/commitrange.h, src/snmalloc/backend_helpers/largebuddyrange.h, src/snmalloc/ds/allocconfig.h
Using PAGE_SIZE as the minimum size of the CHUNK means that if this is
configured to 2MiB, then there is a gap between
MAX_SMALL_SIZECLASS_SIZE, and MIN_CHUNK_SIZE, and thus
we can't represent certain sizes.
This removes that connection, and adds a static assert to check for the issue.
=> Alter PAGE_SIZE usage

src/snmalloc/ds/flaglock.h, src/snmalloc/pal/pal.h, src/snmalloc/pal/pal_concept.h, src/snmalloc/pal/pal_open_enclave.h, src/snmalloc/pal/pal_posix.h, src/snmalloc/pal/pal_tid_default.h, src/snmalloc/pal/pal_windows.h
Making this part of the PAL allows other platforms to replace with
something more suitable.
=> Add a TID to the PAL

src/snmalloc/backend/meta_protected_range.h, src/snmalloc/backend/standard_range.h, src/snmalloc/backend_helpers/commitrange.h, src/snmalloc/backend_helpers/globalrange.h, src/snmalloc/backend_helpers/largebuddyrange.h, src/snmalloc/backend_helpers/logrange.h, src/snmalloc/backend_helpers/pagemapregisterrange.h, src/snmalloc/backend_helpers/range_helpers.h, src/snmalloc/backend_helpers/smallbuddyrange.h, src/snmalloc/backend_helpers/statsrange.h, src/snmalloc/backend_helpers/subrange.h
This way, we don't have to specify a Parent when we're just interested in
Pipe-ing things together.
We could have called these inner classes Apply and left the Pipe implementation
alone, but it's probably better to call them Type and adjust the Pipe code.
This commit is **absolutely** best reviewed ignoring whitespace changes!
This commit also conflicts, for trivial reasons, with #530.  I would be tempted to wait until that has landed and then commute this back across that if we want this.
=> RFC, NFC: refactor ranges to be nested templates

CMakeLists.txt, src/snmalloc/pal/pal_linux.h
The particular system to support here is centos 7 with 
* kernel-headers for kernel 3.10.0
* glibc 2.17
Issued with that platform:
* `MADV_FREE` undefined
* `GRND_NONBLOCK` not defined as there is no `sys/random.h`
Fixes #544
=> Support older linux systems

src/snmalloc/pal/pal_linux.h
Horribly sorry, i fatfingered the wrong ifdef around the missing `MADV_FREE` flag on older linux systems (kernel-headers < 4.5).
=> Fix wrong ifdef in pal_linux.h

src/snmalloc/ds_core/helpers.h
Otherwise, on platforms for which {,u}intptr_t aren't just typedef-s of
other scalar types, it's ambiguous which way an implicit cast should go.
=> Add buffer append method for {,u}intptr_t

.github/workflows/morello.yml
For review and commentary.  If you want to test this and need access to the cluster, please let me know.  We should not merge this until R&CT 4968 is fully approved and the automation is actually set up in the right place on Azure.  (If that happens before CHERI support in `snmalloc`, we can just disable the Purecap builds herein.)
See https://github.com/nwf-msr/snmalloc/actions/runs/2385794002 for an example run.  The Purecap Release variant does not, at present, build, due to https://github.com/CTSRD-CHERI/llvm-project/issues/618, and the Purecap Debug variant does not build either, presumably just because we're missing a CHERI AAL and PAL.  (I haven't looked in detail.)
=> Add Morello CI

src/snmalloc/mem/localalloc.h
Although, double frees are generally caught on large allocs.  This is
done very late in the process after many operations more operations have
occurred.
This change brings that check much earlier in the process.
=> Add stricter double free checking on large allocs

src/snmalloc/aal/address.h, src/snmalloc/global/memcpy.h, src/test/func/cheri/cheri.cc, src/test/perf/memcpy/memcpy.cc
More Lincoln Logs-style work, mostly: assemble existing pieces differently for a `StrictProvenance` / CHERI-aware `memcpy`.  As documented, there are two constraints in tension:
- We must use capability load and store instructions wherever possible, so that our `memcpy` obliviously copies capabilities (and preserves tags) during its operation.
- We cannot use capability load or store instructions at misaligned addresses, since those (are permitted to) trap.
Therefore, we have three cases to consider:
1. copies too small to move a capability: use a jump table of _data word_ copies and be done with it
2. "equally (mis)aligned" source and targets: these may have a (naturally aligned) capability inside the source that would also land at a naturally aligned destination address: perform _data …
=> memcpy vs StrictProvenance

src/snmalloc/backend_helpers/globalrange.h, src/snmalloc/backend_helpers/lockrange.h, src/snmalloc/backend_helpers/staticrange.h
Pull a part the locking from the static range. This enables
locking to be added to a range directly, and does not require
it to be made static.  This is useful in cases where the source
of memory is shared between threads, but not static.  I.e. there
are multiple instances of the same type.
=> Separate locking from static range

.github/workflows/main.yml
* Remove TSAN Debug - it takes too long, and it is not clear it adds any additional checking over TSAN Release build
* Require TSAN to pass for approval - TSAN this was not initially enabled as there were issues, but it has been stable for a long time, so can be part of the approval process.
=> TSAN CI changes

src/snmalloc/aal/aal.h, src/snmalloc/aal/aal_cheri.h, src/snmalloc/aal/aal_concept.h, src/snmalloc/backend/backend.h, src/test/func/cheri/cheri.cc
While here, add a test that our sizeclasses are fixed points of the rounding function.
This matters now that some bigger things are to be sourced from the metadata Range; see #556.
=> Introduce AAL hook for CHERI representable length rounding

src/snmalloc/aal/aal_cheri.h, src/snmalloc/backend/backend.h, src/snmalloc/backend_helpers/smallbuddyrange.h, src/snmalloc/mem/backend_concept.h, src/snmalloc/mem/pool.h, src/test/func/pool/pool.cc
Verona was using a pool allocator to requests large pieces of meta-data. This was broken with the current design, so the smallbuddy can now pass requests up if they are too large.
=> Make smallbuddy handle larger requests correctly

src/snmalloc/backend_helpers/pagemap.h, src/test/func/pagemap/pagemap.cc
This PR ensures that if a pagemap is used in a fixed region that has very large granularity it does require undue additional alignment.
=> Pagemap Rounding

src/snmalloc/aal/aal.h, src/snmalloc/backend_helpers/commonconfig.h, src/snmalloc/ds_core/bits.h, src/snmalloc/mem/backend_wrappers.h, src/snmalloc/mem/sizeclasstable.h, src/snmalloc/pal/pal_consts.h
`constexpr` => `inline`
and when not in a class scope
`constexpr` => `static`
This PR removes the redundant use of `inline` and `static`.  It also prefers
`static constexpr`
over
`constexpr static`
=> [NFC] Simplify static constexpr inline

src/snmalloc/backend/backend.h, src/snmalloc/backend_helpers/buddy.h, src/snmalloc/backend_helpers/defaultpagemapentry.h, src/snmalloc/backend_helpers/smallbuddyrange.h, src/snmalloc/ds_core/seqset.h, src/snmalloc/mem/corealloc.h, src/snmalloc/mem/metadata.h
This changes the representation of SeqSet to be doubly linked.  This is required to enable tracking fully used slabs.
* Currently debug_check_empty can say empty when it isn't as a slab is fully used.
* Implementing a heap walk we will also need to track fully used slabs.
Future PR will use this to track fully used slabs.
=> Change representation of the SeqSet

.github/workflows/main.yml, src/snmalloc/ds/aba.h, src/snmalloc/mem/pooled.h
Fallout from https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/
=> Catch CI up with github

src/snmalloc/aal/address.h, src/snmalloc/ds_core/seqset.h, src/snmalloc/mem/corealloc.h, src/snmalloc/mem/freelist.h, src/snmalloc/mem/localalloc.h, src/snmalloc/mem/metadata.h, src/snmalloc/mem/remotecache.h, src/test/func/statistics/stats.cc
This includes a two changes that are on the way to implementing heap walk.  The changes performed are:
* Track the `laden` ranges of memory: the full and almost full slabs and large allocations.
* Ensure each slab metadata knows what range of memory it is describing.  This was not previously the case for a fully used slab where there is no free list.
=> Towards heap walk

src/snmalloc/mem/sizeclasstable.h
Nesting the class inside a function generates bad code in Debug (#584). Unnesting seems to fix this.
=> Remove class nesting

src/snmalloc/ds_core/defines.h
Compiler versions do not imply standard library versions, and even where the compiler and standard library versions were matched, this check was wrong.
=> Replace fragile and wrong check for library feature.

.github/workflows/main.yml, CMakeLists.txt
This uses VirtualBox instead of xhyve.  It might be slower, but should be more reliable.
=> Try vm-actions instead of cross-platform-actions

.github/workflows/morello.yml
Motivated by not pinning us to the 2022.05 release any more; other changes while in the vicinity.
=> Update Morello CI

src/snmalloc/override/malloc.cc
When using dlopen with RTL_DEEPBIND the LD_PRELOAD used by the majority of allocators does not work as both libc and snmallocs allocators can be called by various dso.
This patch uses GLIBC's __malloc_hook to override the allocator as well as LD_PRELOAD.  This means that all libraries will call snmalloc when performing allocation.
=> Alter glibc override to work with RTL_DEEPBIND

src/snmalloc/aal/aal.h
=> AAL disable __builtin_readcyclecounter on macOs arm64.

.github/workflows/main.yml, CMakeLists.txt, docs/PORTING.md, src/snmalloc/backend/globalconfig.h, src/snmalloc/ds/allocconfig.h, src/snmalloc/ds/pagemap.h, src/snmalloc/ds_core/defines.h, src/snmalloc/ds_core/ds_core.h, src/snmalloc/ds_core/helpers.h, src/snmalloc/ds_core/mitigations.h, src/snmalloc/mem/corealloc.h, src/snmalloc/mem/freelist.h, src/snmalloc/mem/localalloc.h, src/snmalloc/mem/metadata.h, src/snmalloc/mem/remotecache.h, src/snmalloc/mem/sizeclasstable.h, src/snmalloc/pal/pal_apple.h, src/snmalloc/pal/pal_bsd.h, src/snmalloc/pal/pal_bsd_aligned.h, src/snmalloc/pal/pal_consts.h, src/snmalloc/pal/pal_freebsd.h, src/snmalloc/pal/pal_linux.h, src/snmalloc/pal/pal_posix.h, src/test/func/domestication/domestication.cc, src/test/func/pagemap/pagemap.cc
All the checks and mitigations have been placed under feature flags.
These can be controlled by defining
SNMALLOC_CHECK_CLIENT_MITIGATIONS
This can take a term that represents the mitigations that should be enabled.
E.g.
-DSNMALLOC_CHECK_CLIENT_MITIGATIONS=nochecks+random_pagemap
The CMake uses this to build numerous versions of the LD_PRELOAD library and
tests to allow individual features to be benchmarked.
=> Factor check client into separate features

src/snmalloc/ds_core/ptrwrap.h, src/snmalloc/mem/corealloc.h, src/snmalloc/mem/freelist.h, src/snmalloc/mem/remoteallocator.h
This partially address #586.  It provides a branch on the enqueue path, which simplifies the code.
This removes the need for the smallest size class to be create when the allocator is first initialised.
=> Remote stub

src/snmalloc/backend_helpers/buddy.h, src/snmalloc/ds_core/redblacktree.h
The buddy allocator doesn't need to look at sizes above the current highest size. This commit tracks the highest block that is stored in the buddy allocator.
This is factored out of #570.
=> Optimise buddy allocator to not search too high

docs/BUILDING.md
This PR renames the flag used to enable the import of snmalloc as header-only in the documentation, in line with the name of the flag in [`CMakeLists.txt`](https://github.com/microsoft/snmalloc/blob/7f368bd6dabd6349534550df54a4e559b455cfc7/CMakeLists.txt#L35).
=> Update name of header-only flag in documentation

src/snmalloc/mem/pool.h, src/snmalloc/mem/pooled.h, src/test/func/pool/pool.cc
So allocator churn will cause remote queues to be visited.
=> Made pool reuse a queue

src/snmalloc/backend/fixedglobalconfig.h, src/snmalloc/backend/meta_protected_range.h, src/snmalloc/backend/standard_range.h, src/snmalloc/backend_helpers/backend_helpers.h, src/snmalloc/backend_helpers/staticconditionalrange.h, src/snmalloc/ds/allocconfig.h
This PR adds a new type of Range that can allow a range to be disabled dynamically. 
This is used to disable some backend caching if the heap is very small, such as in the OpenEnclave case.
=> Conditional range

src/snmalloc/ds_core/redblacktree.h, src/snmalloc/mem/localalloc.h, src/snmalloc/mem/sizeclasstable.h, src/snmalloc/override/libc.h, src/snmalloc/override/malloc.cc, src/snmalloc/override/new.cc, src/snmalloc/snmalloc_front.h
This pulls the main definitions of the various libc malloc functions into a header for easier use and inclusion in other projects.
=> Factor out libc code into a header.

CMakeLists.txt, src/snmalloc/aal/aal.h, src/snmalloc/aal/aal_arm.h, src/snmalloc/aal/aal_x86.h
The prefetching is always used to move the cache line to the current core for writing.  This change makes it use exclusive mode prefetch and enables it as a feature flag for x64.
=> Using exclusive mode prefetch

src/snmalloc/ds_core/seqset.h
This allows them to exist as fields without invalidating the set.
This should make it possible to remove the undefined behaviour in the creation of FrontendSlabMetadata, which is currently created via a reinterpret_cast from a different-typed allocation. FrontendSlabMetadata has a SeqSet::Node field that is in an unspecified state on construction and which is valid only when inserted into a SeqSet.
=> Add a default constructor to seqset nodes.

src/snmalloc/mem/corealloc.h, src/snmalloc/mem/localalloc.h, src/snmalloc/mem/pool.h, src/snmalloc/mem/pooled.h, src/test/func/cheri/cheri.cc, src/test/func/pool/pool.cc
The Pool class is used by verona-rt.  The recent changes made this less nice to consume as an API.
This change makes the construction logic a template parameter to the Pool. This enables standard allocation to be used from Verona.
Fixes #603
=> Template construction of Pool elements

.github/workflows/main.yml
Fix https://github.com/actions/runner-images/issues/8659
=> Workaround runner issue.

src/snmalloc/mem/corealloc.h, src/snmalloc/mem/metadata.h, src/snmalloc/mem/remoteallocator.h, src/snmalloc/override/libc.h
As usual, (my) long-running PRs tend to accumulate other, less-relevant things.  Pull some of those out for independent review.
=> Pull some small things off the bottom of #637

.github/workflows/main.yml, src/snmalloc/aal/aal.h, src/snmalloc/aal/aal_arm.h, src/snmalloc/ds_core/bits.h
This PR solves a few issues when building for Windows on ARM:
1. No detection for the Windows ARM64 architecture, resulting in no AAL being selected.
2. A compilation error in `bits.h` due to the use of Intel intrinsics that don't exist on ARM.
3. A misdetection of the ARM64EC ABI as AMD64, leading to the use of an unsupported Intel intrinsic.
The first two issues manifest as follows. You can repro in an [ARM64 Visual Studio Developer Command Prompt](https://devblogs.microsoft.com/cppblog/arm64ec-support-in-visual-studio/#developer-command-prompt):
```
> cl /nologo /diagnostics:caret /EHsc /std:c++20 /c malloc.cc
ds_core\bits.h(162,14): error C3861: '_tzcnt_u64': identifier not found
return _tzcnt_u64(static_cast<unsigned __int64>(x));
^
ds_core\bits.h(208,21): error C3861: '_umul128': …
```
=> Add Windows ARM64 support

src/snmalloc/override/libc.h
With [DR460](https://open-std.org/JTC1/SC22/WG14/www/docs/summary.htm#dr_460) the undefined behaviour for size not being a multiple of alignment was remove.
The [N2072](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2072.htm) allows for this to return memory.
So we can remove this assert and keep the same conditions as memalign.
=> Remove unnecessary assertion from aligned_alloc

CMakeLists.txt, src/snmalloc/override/new.cc
Produce static library that only overrides new and delete. This allows for a static library to be added that only overrides new and delete.
=> Refactor new/delete overrides

src/snmalloc/mem/corealloc.h, src/snmalloc/mem/freelist.h, src/snmalloc/mem/freelist_queue.h, src/snmalloc/mem/metadata.h, src/snmalloc/mem/remoteallocator.h, src/snmalloc/mem/remotecache.h, src/test/perf/msgpass/msgpass.cc
This is just enough of #637 to get the benchmark itself landed, but that also pulls in the freelist refactoring and the option of tweaking obfuscation keys (but not any usage of that internally).
It's probably worth getting someone with more cryptographic and/or red-teaming chops to think about the particular tweaking function, too.
=> msgpass benchmark and its refactoring dependencies

src/snmalloc/backend_helpers/buddy.h, src/snmalloc/ds/pagemap.h, src/snmalloc/pal/pal_consts.h, src/snmalloc/pal/pal_freebsd.h, src/snmalloc/pal/pal_linux.h
This improves the startup time for a heavily multi-threaded workload.
There are two improvements that are independent of each other:
1.  Buddy allocator has local cache.  The buddy allocator uses the pagemap as backing store.  This means that a lot of pages are faulted in at startup for the pagemap, when a large unaligned block is added.  This was causing a noticeable time in micro-profiling. The change in this PR makes there be a few entries at the top-level, so we only use the pagemap once a reasonable amount entries are required.
2. DODUMP/DONTDUMP on Linux were costing a noticeable amount of time, and causing a significant slow down.  This PR also exposes a new couple of optional operations on the PAL, and only applies these operations to the Pagemap.
=> Startup speed

CMakeLists.txt, src/snmalloc/ds_core/defines.h
An attempt to simplify some `#ifdef` mazes (for `[[no_unique_address]]`) led me to want to test the compiler more directly, which meant that `SNMALLOC_USE_CXX17` was largely superfluous, so we can remove it in favor of testing pre-defined preprocessor symbols directly.
In a little more detail, the prior definitions were not sufficient to detect when `[[no_unique_address]]` would be accepted but ignored.  That made deciding when we could kick on #637 by default more... interesting.  With this, I hope to have a simpler time of things.
=> Remove the SNMALLOC_USE_CXX17 C preprocessor symbol

src/snmalloc/backend/globalconfig.h, src/snmalloc/backend_helpers/lockrange.h, src/snmalloc/ds/combininglock.h, src/snmalloc/ds/ds.h, src/snmalloc/ds/flaglock.h, src/snmalloc/ds/singleton.h, src/snmalloc/mem/pool.h
This is hybrid of Flat Combining and the MCS queue lock. It uses
the queue like the MCS queue lock, but each item additionally
contains a thunk to perform the body of the lock. This enables
other threads to perform the work that initially issued the request.
=> Implement MCS Combining lock

src/snmalloc/global/libc.h
posix_memalign() requires alignment values of at least sizeof(uintptr_t), but aligned_alloc() does not.  memalign() regressed to require larger alignment in commit
6cbc50fe2c255b5b47ea63f4cf759a6a20f6e7a6.
Fixes #668
=> aligned_alloc: Permit alignment values smaller than sizeof(uintptr_t)

src/snmalloc/backend/meta_protected_range.h, src/snmalloc/backend_helpers/backend_helpers.h, src/snmalloc/backend_helpers/buddy.h, src/snmalloc/backend_helpers/noprange.h
`Buddy` ranges can be instantiated with `MAX_SIZE_BITS == MIN_SIZE_BITS` (or, in principle, `<=`).  If this happens, the resulting class will contain 0-length arrays, and code that appears to attempt to access an element therein trips gcc's `-Warray-bounds`.
This PR contains two commits: one that adds a `static_assert` to ensure that `Buddy`'s arrays are always of positive size, and one possible way to fix the case I'm tripping over.  The latter works because the Buddy's `MIN_SIZE_BITS` is instantiated at `MIN_CHUNK_BITS`, and so the change herein then ensures that its `MAX_SIZE_BITS` is strictly greater than `MIN_CHUNK_BITS`.
A different, and possibly better, solution would be to drop the `LargeBuddyRange` from `CentralMetaRange` when `max_page_chunk_size_bits` is computed to be equal to …
=> 0-length arrays in Buddy ranges

CMakeLists.txt, src/snmalloc/aal/aal.h, src/snmalloc/backend/globalconfig.h, src/snmalloc/backend_helpers/largebuddyrange.h, src/snmalloc/ds/allocconfig.h, src/snmalloc/ds_core/bits.h, src/snmalloc/mem/corealloc.h, src/snmalloc/mem/entropy.h, src/snmalloc/mem/freelist.h, src/snmalloc/mem/localalloc.h, src/snmalloc/mem/localcache.h, src/snmalloc/mem/metadata.h, src/snmalloc/mem/remotecache.h, src/snmalloc/mem/sizeclasstable.h, src/test/func/domestication/domestication.cc, src/test/perf/contention/contention.cc
A prefix of #637 as requested by @mjp41.
=> Bottom commits from BatchIt

src/test/perf/startup/startup.cc
In test/perf/startup, gcc (Debian 14.2.0-3) seems to get confused about the size of the counters vector as the code was written.  Rewrite the code to pass the same value (`std::thread::hardware_concurrency()`, but in a local) to both `counters.resize()` and the `ParallelTest` ctor.
=> Further gcc -Werror=array-bounds fix

src/test/perf/singlethread/singlethread.cc
When building test/perf/singlethread to use the system allocator, gcc (Debian 14.2.0-3) correctly sees that we were using the value of a pointer after it had been passed to the privileged free(), which is UB.
Flip the check and dealloc, so that we query the set of pointers we're tracking first, using the pointer while the allocation is still live.
=> gcc UAF warning in test/perf/singlethread -malloc

CMakeLists.txt, src/snmalloc/backend/backend.h, src/snmalloc/ds/allocconfig.h, src/snmalloc/mem/corealloc.h, src/snmalloc/mem/freelist.h, src/snmalloc/mem/localalloc.h, src/snmalloc/mem/metadata.h, src/snmalloc/mem/remoteallocator.h, src/snmalloc/mem/remotecache.h
This recreates the current contents of #637 from a different repository, since the lifetime of the @nwf-msr account is now pretty limited.  (I couldn't find a way to move _branches_ between repos in a way that swung the PR, so had to settle for this low-tech solution.)
=> WIP: BatchIt

CMakeLists.txt, src/snmalloc/pal/pal_posix.h
This uses the PAGESIZE constant from the unistd.h on POSIX. This should make the code more resilient to being compiled on platforms with different page sizes.
=> Provide option to CMake for Page Size

src/snmalloc/override/malloc.cc
in addition, specs requires size to be a multiple of alignment.
=> aligned_alloc requirements update.

src/snmalloc/backend_helpers/largebuddyrange.h, src/snmalloc/ds/combininglock.h, src/snmalloc/ds/flaglock.h, src/snmalloc/ds/singleton.h, src/snmalloc/ds_core/helpers.h, src/snmalloc/ds_core/redblacktree.h, src/snmalloc/mem/freelist_queue.h, src/snmalloc/mem/remoteallocator.h, src/snmalloc/pal/pal_consts.h, src/snmalloc/pal/pal_ds.h, src/test/func/redblack/redblack.cc, src/test/perf/startup/startup.cc
=> Remove some unneeded headers

src/snmalloc/pal/pal_haiku.h, src/snmalloc/pal/pal_posix.h
Also fixing the build with PAL::posix assuming the intent is to avoid using std namespace for max but rather using the in-house implementation.
=> PAL::haiku finally supports getentropy.

.github/workflows/main.yml, .gitignore, CMakeLists.txt, src/snmalloc/ds/combininglock.h, src/snmalloc/pal/pal_apple.h, src/snmalloc/pal/pal_consts.h, src/snmalloc/pal/pal_freebsd.h, src/snmalloc/pal/pal_linux.h, src/snmalloc/pal/pal_windows.h
```
./perf-startup-fast | head -n1 | awk -e '{print $2;}' 
```
Results:
```
diff -y futex nofutex
9021562                                                       | 7005614
7032388                                                       | 6074838
5520130                                                       | 8339826
7180558                                                       | 7456548
5003988                                                       | 8501328
5444736                                                       | 8336394
5910520                                                       | 7088290
6360882                                                       | 5502706
5328400                                                       | 8408862
5326002 …
```
=> implement polite waiting

src/snmalloc/global/memcpy.h, src/snmalloc/override/memcpy.cc, src/test/func/memcpy/func-memcpy.cc
mostly like memcpy with optional bound checking but capable of handling overlapping cases thus using
reverse copy instead.
=> custom memmove implementation proposal.

CMakeLists.txt, fuzzing/CMakeLists.txt, fuzzing/snmalloc-fuzzer.cpp
To test, set
```
"SNMALLOC_ENABLE_FUZZING": "ON"
"FUZZTEST_FUZZING_MODE": "ON"
```
to cmake configuration.
Then,
```
cmake --build <build> --target snmalloc-fuzzer
```
Then,
```
<build>/fuzzing/snmalloc-fuzzer --fuzz=snmalloc_fuzzing.forward_memmove
```
I get the following error for `snmalloc_fuzzing.forward_memmove`:
```
schrodinger@Homotopy:~/snmalloc/build$ ./fuzzing/snmalloc-fuzzer --fuzz=snmalloc_fuzzing.forward_memmove
[.] Sanitizer coverage enabled. Counter map size: 44409, Cmp map size: 262144
Note: Google Test filter = snmalloc_fuzzing.forward_memmove
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from snmalloc_fuzzing
[ RUN      ] snmalloc_fuzzing.forward_memmove …
```
=> fuzzing test and detect the memmove error

fuzzing/snmalloc-fuzzer.cpp, src/snmalloc/global/memcpy.h, src/snmalloc/override/memcpy.cc, src/test/func/memcpy/func-memcpy.cc
This reverts commit 01885f5a042f1ba7812d18df36b4ec76b0ad8b40.
=> Revert "custom memmove implementation proposal. (#593)"

CMakeLists.txt
all 3rd party packages are located in /usr/pkg so we lessen the burden to set these.
=> neasing netbsd build.

src/snmalloc/aal/aal.h, src/snmalloc/ds_core/defines.h, src/snmalloc/pal/pal_posix.h, src/snmalloc/pal/pal_timer_default.h
Avoid pulling in non freestanding chrono dependency if we can use `clock_gettime`.
=> avoid chrono inclusion when clock_gettime is available

docs/BUILDING.md
Hello snmalloc developers. I was going through the build in my project and saw a couple of things that might need updating.
First, it looks like Visual Studio 15 aligns with 2017, not 2019.
It appears this style of generator name "Visual Studio 15 2019 Win64" are for compatibility with CMake versions before 3.1 which was around 2014. In modern CMake, the Visual Studio generator is specified like so:
cmake -G "Visual Studio 15 2017" -A Win32
cmake -G "Visual Studio 15 2017" -A x64
cmake -G "Visual Studio 15 2017" -A ARM
cmake -G "Visual Studio 15 2017" -A ARM64
Since you mention VS 2022 being used in CI regularly, it seems like that should be the generator used in the doc.
The path to malloc.cc and new.cc seem incorrect. Maybe it changed overtime and wasn't updated in the doc.
=> Updating the build doc

CMakeLists.txt
This makes the `_HAS_EXCEPTIONS` flag on windows only apply to libraries, and not if the library is used header only.
=> Fixes: Sets `_HAS_EXCEPTIONS=0` globally #701

src/snmalloc/override/malloc.cc
When using snmalloc in my project as the "header-only library" style, I got a compile error for _msize:
`override\malloc.cc(45,10): error C2733: '_msize': you cannot overload a function with 'extern "C"' linkage`
I believe this is caused by the malloc.cc implementation using MALLOC_USABLE_SIZE_QUALIFIER which resolves to 'const', which is needed by malloc_usable_size's parameter (which _msize gets passed to). I think we must leave 'const' off of _msize's 'void*' parameter and it is ok to then pass as 'const void*' since it is becoming more restrictive.
With this fix my project can build and run successfully.
=> The _msize function has a non-const void* parameter in the msvc CRT.

CMakeLists.txt, src/snmalloc/ds/allocconfig.h, src/snmalloc/mem/corealloc.h
When processing a remote batch, the system will process every single message that was available at the start of processing. This can lead to a long pause time if there have been a considerable number of frees to this thread.
This commit introduces a new mechanism to only process messages up to a limit of 1MiB. The limit is configurable using CMake.
Choosing too small a limit can cause freeing to never catch up with the incoming messages.
=> Limit remote batch size

src/snmalloc/ds_core/defines.h, src/snmalloc/ds_core/mitigations.h, src/snmalloc/ds_core/redblacktree.h, src/snmalloc/global/bounds_checks.h, src/snmalloc/pal/pal_apple.h, src/snmalloc/pal/pal_bsd.h, src/snmalloc/pal/pal_freebsd.h, src/snmalloc/pal/pal_linux.h, src/snmalloc/pal/pal_posix.h, src/test/perf/external_pointer/externalpointer.cc
Defining the constexpr DEBUG caused problems when building SNMALLOC into our project. This change simply changes the constexpr's name to SNMALLOC_DEBUG.
=> Changing DEBUG constexpr to SNMALLOC_DEBUG

src/snmalloc/aal/aal.h, src/snmalloc/aal/aal_arm.h, src/snmalloc/aal/aal_consts.h, src/snmalloc/aal/address.h, src/snmalloc/ds/aba.h, src/snmalloc/ds_core/bits.h, src/snmalloc/ds_core/defines.h, src/snmalloc/ds_core/helpers.h, src/snmalloc/ds_core/mitigations.h, src/snmalloc/ds_core/redblacktree.h, src/snmalloc/ds_core/seqset.h, src/snmalloc/mem/entropy.h, src/snmalloc/mem/freelist.h, src/snmalloc/mem/localalloc.h, src/snmalloc/mem/ticker.h, src/snmalloc/override/jemalloc_compat.cc, src/snmalloc/override/rust.cc, src/snmalloc/pal/pal_concept.h, src/snmalloc/pal/pal_noalloc.h, src/snmalloc/pal/pal_posix.h, src/test/func/jemalloc/jemalloc.cc
Stacked on:
- #715 
- #717 
- #718 
- #719
=> [proxy](5/n) use c headers instead of c++ headers

docs/combininglock.md, src/snmalloc/aal/aal.h, src/snmalloc/backend/backend.h, src/snmalloc/backend/fixedglobalconfig.h, src/snmalloc/backend_helpers/pagemap.h, src/snmalloc/ds/combininglock.h, src/snmalloc/ds/pagemap.h, src/snmalloc/ds_aal/flaglock.h, src/snmalloc/ds_core/helpers.h, src/snmalloc/ds_core/seqset.h, src/snmalloc/mem/backend_concept.h, src/snmalloc/mem/backend_wrappers.h, src/snmalloc/mem/freelist.h, src/snmalloc/mem/localalloc.h, src/snmalloc/mem/metadata.h, src/snmalloc/mem/remoteallocator.h, src/snmalloc/pal/pal.h, src/snmalloc/pal/pal_posix.h, src/snmalloc/stl/cxx/utility.h, src/snmalloc/stl/gnu/type_traits.h, src/snmalloc/stl/gnu/utility.h, src/snmalloc/stl/utility.h
=> [proxy](6/n) self-vendor utility headers

src/snmalloc/pal/pal_windows.h
The Pagemap can potentially be accessed where there is no direct
knowledge of the location.  On platforms with lazy commit this can
be handled by the OS faulting in a zero page.  Here we modify the
Windows PAL to add an exception handler that will commit pages
in the read only range, i.e. the page map.  We still require explicit
notify_using to be able to modify the pagemap.
Stacked on top of #725
=> Add Windows Support for Lazy Commit of page map

src/snmalloc/pal/pal_linux.h, src/snmalloc/pal/pal_posix.h
Use the definition from `stdio.h` directly. Manually defining such symbol may lead to mismatched exception spec.
```
/code/snmalloc/src/snmalloc/backend_helpers/../mem/../ds/../pal/pal_linux.h:22:16: error: 'puts' is missing exception specification 'throw()'
22 | extern "C" int puts(const char* str);
|                ^
|                                      throw()
/code/snmalloc/src/snmalloc/backend_helpers/../mem/../ds/../pal/pal_posix.h:26:16: note: previous declaration is here
26 | extern "C" int puts(const char* str);
|                ^
1 error generated.
ninja: build stopped: subcommand failed.
```
=> remove extra puts definitions

src/snmalloc/ds/combininglock.h, src/snmalloc/pal/pal_apple.h, src/snmalloc/pal/pal_freebsd.h, src/snmalloc/pal/pal_linux.h, src/snmalloc/pal/pal_openbsd.h, src/snmalloc/pal/pal_windows.h, src/test/perf/lotsofthreads/lotsofthread.cc
This fixes a bug in multiple Pals that could return from wake on address spuriously.
The Linux man page (https://www.man7.org/linux/man-pages/man2/futex.2.html#RETURN_VALUE)
says:
FUTEX_WAIT
Returns 0 if the caller was woken up.  Note that a wake-up
can also be caused by common futex usage patterns in
unrelated code that happened to have previously used the
futex word's memory location (e.g., typical futex-based
implementations of Pthreads mutexes can cause this under
some conditions).  Therefore, callers should always
conservatively assume that a return value of 0 can mean a
spurious wake-up, and use the futex word's value (i.e., the
user-space synchronization scheme) to decide whether to
continue to block or not.
But the code could return without rechecking the the value had actually …
=> Multiple Pals could return spuriously from wake on address

.github/workflows/main.yml
Add newer platforms to CI.
* ubuntu-24.04-arm
* windows-2021
* windows-2025
=> CI: Refresh Targets

.github/workflows/main.yml, src/snmalloc/override/new.cc
With STL no longer being included by the primary headers the `new.cc` override needs to include `<new>` to get `nothrow`
=> build: Fix nothrow include.

CMakeLists.txt, src/snmalloc/ds/combininglock.h, src/snmalloc/ds_aal/ds_aal.h, src/snmalloc/ds_aal/flaglock.h, src/snmalloc/ds_aal/prevent_fork.h, src/snmalloc/ds_aal/singleton.h, src/snmalloc/mem/freelist_queue.h, src/snmalloc/stl/gnu/atomic.h, src/test/func/protect_fork/protect_fork.cc
If a thread forks, while another thread is holding an snmalloc lock, then the allocator could stop working.
This patch attempts to protect against the cases of this. There is one case that is not covered. If a fork occurs during the very first allocation. This can result in the installation of the fork handler racing with the fork, and all bets are off.
Address #630
=> Protection against fork

src/snmalloc/ds/pagemap.h, src/test/func/fixed_region_alloc/fixed_region_alloc.cc
When using a fixed region configuration, the pagemap needs the address to be a relative offset to the base address in order to calculate the correct range for the reservation. Without this change it will try to reserve outside of the given region.
We could just always subtract the base address without the additional if checks since base is 0 when no fixed region is configured and thus would result in no change. However, the additional checks make it clearer to the reader that this is for the bounded use-case. It is also consistent with the other functions that need similar adjustments.
=> Fixed pagemap reservations for a fixed-region use-case using the default PAL

src/snmalloc/global/bounds_checks.h, src/snmalloc/global/globalalloc.h, src/snmalloc/global/memcpy.h, src/test/perf/memcpy/memcpy.cc
This changes the shape of check_bounds to take a continuation to call if the bounds check succeeds.  This is designed to allow for easily wrapping existing code with a bounds check, e.g.
```
void* memcpy(void* dest, const void* src, size_t n) {
return check_bounds(dest, n, [&] {
return memcpy_impl(dest, src, n);
});
}
```
=> Refactor check_bounds

src/test/func/memory/memory.cc
Fix tests for external pointer with GWP-Asan.  There was a latent bug in the conditions being checked in some of the func-memory tests. See here for the failure:
https://github.com/microsoft/snmalloc/actions/runs/13832280098/job/38699118822
This PR fixes the conditions and causes the tests to be run multiple times to increase the likelihood of GWP-Asan failing.
=> Fix test when using GWP-Asan

src/snmalloc/pal/pal_windows.h
When using snmalloc as header-only library in a project that globally defines `WIN32_LEAN_AND_MEAN`, there is a compile error for macro redefinition.
Guard the pal_windows.h define.
=> Header-only build fix for WIN32_LEAN_AND_MEAN redefinition

src/snmalloc/mem/pool.h, src/test/func/pool/pool.cc
The pool sort routine is used by Verona's systematic testing.  There was a bug introduced in #612 that could corrupt the list when a sort occured.
This is not used by snmalloc and the test coverage was insufficient to expose the bug.
This PR fixes the bug, and improves test coverage.
=> Fix bug in pool sort

src/snmalloc/pal/pal_windows.h, src/test/perf/lotsofthreads/lotsofthread.cc
Continuation of: https://github.com/microsoft/snmalloc/pull/771. I made a new PR since it was a somewhat different concept from the original.
This seems to be a more correct way to cleanup at the end of the program or DLL.
1. Reservations are tracked in a static vector
2. This vector is a custom one that use VirtualAlloc and VirtualFree to avoid recursive calls
3. When it's time to exit, free the reservations we have created
4. #pragma init_seg(".CRT$XCB") is used to set this translation unit to be very early in the initialization phase. This means that our cleanup function passed to atexit() gets called at the very end, and our cleanup code can work properly.
=> Release all pagemap reservations at the very end of the program or DLL

src/test/func/memory/memory.cc
Some CI pipelines were occasionally timing out due to the func-memory test taking too long. This change reduces the number of iterations from 100 to 50 for each test run, which should help avoid timeouts while still providing sufficient coverage.
It also adds some debug output to indicate the time taken for each test.
=> Adjust func-memory test to be shorter.

docs/PORTING.md, src/snmalloc/backend_helpers/authmap.h, src/snmalloc/backend_helpers/commitrange.h, src/snmalloc/backend_helpers/pagemap.h, src/snmalloc/backend_helpers/pagemapregisterrange.h, src/snmalloc/ds/pagemap.h, src/snmalloc/mem/backend_concept.h, src/snmalloc/pal/pal_apple.h, src/snmalloc/pal/pal_concept.h, src/snmalloc/pal/pal_freebsd_kernel.h, src/snmalloc/pal/pal_noalloc.h, src/snmalloc/pal/pal_plain.h, src/snmalloc/pal/pal_posix.h, src/snmalloc/pal/pal_windows.h
On Windows, the most common way to out-of-memory is to fail to commit a page.  The current design of the Pal assumes that notify_using always succeeds, thus we have to raise an error if it fails.  This changes the specification of notify_using to return a bool, indicating whether the notify succeeded or not.
This allows Windows to fail the notification, and then the surrounding code can handle the failure appropriately, such as by throwing an exception or returning the nullptr for the allocation.
=> Fallible notify using

src/snmalloc/mem/corealloc.h, src/snmalloc/mem/freelist_queue.h, src/snmalloc/mem/remotecache.h
This PR adds some inlining attributes to lambdas on the fast path.  Some versions of g++ and clang++ were not inlining as much as expected, and leading to poor codegen.  This PR fixes that.
Additionally, it disables the fork prevention during remote allocator posting.  This was visible in some traces as causing a bottleneck.
=> Code Quality - inlining
